### ISSUE TITLE
PySpark

### ISSUE THREAD

**Issue by evenv** [awslabs/deequ#105]
This looks brilliant! Is there support for Pyspark, or is this planned?

**Comment by wcallag3** [comment]
> This looks brilliant! Is there support for Pyspark, or is this planned?

Wondering this as well!

**Comment by sscdotopen** [comment]
Hi,

We don't have plans for pyspark support at the moment, as this would probably require us to duplicate and maintain our complete user-facing API in python. 

We would however be open to external contributions in that direction and would be happy to help and coordinate such an effort.
