### ISSUE TITLE
Check for column values being present in a different data frame column

### ISSUE THREAD

**Issue by paulsukow** [awslabs/deequ#106]
A check for column values being present in a different data frame would be nice. It would be similar to the isContainedIn check, but using a column in a different data frame. The isContainedIn check is limited since there can only be so many values passed in the with the allowedValues array.

This is a simple use case for the check:
We have a data frame with a column of valid postal zip codes. 
For the data frame we are running checks on we want to make sure a given column's values are present in the postal zip codes data frame

**Comment by paulsukow** [comment]
I tried to do something similar with a satisfies check and a sql table, but I couldn't get it work.

```
check.satisfies(column_name IN (SELECT zip_column FROM valid_addresses_table), ...
```

But got an exception 
```
org.apache.spark.sql.AnalysisException: IN/EXISTS predicate sub-queries can only be used in a Filter: Aggregate
```

I was thinking that this could work since the columnCondition description for the satisfies check is 
```
    * @param columnCondition Data frame column which is a combination of expression and the column
    *                        name. It has to comply with Spark SQL syntax.
    *                        Can be written in an exact same way with conditions inside the
    *                        `WHERE` clause.
```
 
and looking at https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/2728434780191932/1483312212640900/6987336228780374/latest.html
the sql is valid

**Comment by sscdotopen** [comment]
At the moment our design assumes that there is only a single dataframe on which we evaluate the constraints. A simple workaround for you could be to manually collect all distinct values from the other dataframe and use them in a ```isContainedIn``` check.
