### ISSUE TITLE
Maven central release for new spark/scala version

### ISSUE THREAD

**Issue by Obarros** [awslabs/deequ#108]
Hi, 

I was trying to find a version compatible with spark 2.3/2.4 and scala 2.12.x.  

It seems that we don't have any available on maven central.

Is this something on the Roadmap? 

Does having a release pipeline implemented with cross building/compiling support help this?

**Comment by sscdotopen** [comment]
Hi,

We can create a version with 2.12 that compiles and passes simple tests, but we haven't tried it on larger jobs yet. If you want, we can build an experimental jar for you.

**Comment by Obarros** [comment]
Hi, Thanks for the updated. 
That would be great.

Are there docs or so on what is is the release process at the moment? 
Do we automate the check on larger jobs? 
Can we automate it somehow?

I would be keen to help if those sort of features align with the roadmap you have.

**Comment by iamsteps** [comment]
Hi Obarros,

I started looking into that issue. Just as a clarification, the currently released version is compatible with Spark 2.3 and 2.4 already. Regarding Scala 2.12, Spark just added [experimental support for Scala 2.12](https://issues.apache.org/jira/browse/SPARK-14220) for 2.4 recently, earlier versions only support 2.11. From some first investigation it looks like we require a few changes to build for Scala 2.12 (especially regarding bumping Scalatest dependencies followed by making the necessary code changes), so please have some patience regarding the release. We will update this issue with further information.

**Comment by javakhishvili** [comment]
Hi,

I second this issue. It would be great to have the Scala 2.12 version of the library.

**Comment by sscdotopen** [comment]
Hi,

Unfortunately, the support for Scala 2.12 in recent Spark versions is only experimental. We would like to wait until Scala is fully supported there.
