### ISSUE TITLE
Usign Deequ with Py4J, Can not instantiate case classes (analyzers)

### ISSUE THREAD

**Issue by QKKQQK** [awslabs/deequ#109]
I'm trying to use Deequ with Py4J and PySpark. Scala classes with constructors and Scala objects can be accessed from the Py4J jvm without problems, but Scala case classes without explicit constructors can not be instantiated. Scala case classes are treated as "JavaClass" in the jvm, but since there's no constructor, I cant not instantiate case classes even with .apply() (function apply not found).

Anyone knows if there's a workaround? (I have to use Python and PySpark, can't use Scala) Thanks!

**Comment by sscdotopen** [comment]
Hi,

I have never tried to instantiate Scala classes from python to be honest. It could be that you need to use the special version of the case class with ```$``` sign at the end to access the ```apply``` method:

https://stackoverflow.com/questions/41570148/why-does-scala-place-a-dollar-sign-at-the-end-of-class-names

Could you give that a try and lets us know if it works?

**Comment by QKKQQK** [comment]
I have tried it before. Since I'm writing Python, it gives syntax error.

**Comment by QKKQQK** [comment]
Solved. I used javap on Deequ Jar file to check the .class files for both class with $ and class without $. Turns out the default Scala parameter values do not work, and have to be filled in with a function call (e.g. com.amazon.deequ.analyzers.Completeness.apply$default$2(), which returns a scala.Option<java.lang.String>). The error was caused by calling a function with missing parameters.

e.g. Running `javap -classpath deequ-1.0.1.jar com/amazon/deequ/analyzers/Completeness` gets the following Completeness class structure:

```
public class com.amazon.deequ.analyzers.Completeness extends com.amazon.deequ.analyzers.StandardScanShareableAnalyzer<com.amazon.deequ.analyzers.NumMatchesAndCount> implements scala.Product, scala.Serializable {
	public static scala.Option<java.lang.String> apply$default$2();
	public static scala.Option<java.lang.String> $lessinit$greater$default$2();
	public static scala.Option<scala.Tuple2<java.lang.String, scala.Option<java.lang.String>>> unapply(com.amazon.deequ.analyzers.Completeness);
	public static com.amazon.deequ.analyzers.Completeness apply(java.lang.String, scala.Option<java.lang.String>);
	public static scala.Function1<scala.Tuple2<java.lang.String, scala.Option<java.lang.String>>, com.amazon.deequ.analyzers.Completeness> tupled();
	public static scala.Function1<java.lang.String, scala.Function1<scala.Option<java.lang.String>, com.amazon.deequ.analyzers.Completeness>> curried();
	public java.lang.String column();
	public scala.Option<java.lang.String> where();
	public scala.Option<com.amazon.deequ.analyzers.NumMatchesAndCount> fromAggregationResult(org.apache.spark.sql.Row, int);
	public scala.collection.Seq<org.apache.spark.sql.Column> aggregationFunctions();
	public scala.collection.Seq<scala.Function1<org.apache.spark.sql.types.StructType, scala.runtime.BoxedUnit>> additionalPreconditions();
	public com.amazon.deequ.analyzers.Completeness copy(java.lang.String, scala.Option<java.lang.String>);
	public java.lang.String copy$default$1();
	public scala.Option<java.lang.String> copy$default$2();
	public java.lang.String productPrefix();
	public int productArity();
	public java.lang.Object productElement(int);
	public scala.collection.Iterator<java.lang.Object> productIterator();
	public boolean canEqual(java.lang.Object);
	public int hashCode();
	public java.lang.String toString();
	public boolean equals(java.lang.Object);
	public com.amazon.deequ.analyzers.Completeness(java.lang.String, scala.Option<java.lang.String>);
}
```

In Python, a function with $ can be called as getattr(FooClass, "Foo$Bar$Function")() since directly calling a function(or using eval()) with $ in function name causes syntax error.

**Comment by sscdotopen** [comment]
Happy to hear that it worked out in the end!

**Comment by cfregly** [comment]
@QKKQQK can you share a sample of your Python code?

**Comment by margitaii** [comment]
Hi, I started to write a [python wrapper](https://github.com/margitaii/pydeequ) for Deequ. I am not a Scala expert but I thought it might be useful for the community to execute Deequ things in pyspark. Currently I cover just the basic functionality of the Deequ API (practically only what is in the examples).  It would be great if I could join others working on something similar...

**Comment by jamiekt** [comment]
> @QKKQQK can you share a sample of your Python code?

More over, could you share a sample of your java/scala code. I'm interested to know how/where you called this and how/if you packaged this so it could be called from Python. 

I can understand the concept of what you've done but am fuzzy on the implementation details. TIA.

**Comment by margitaii** [comment]
@jamiekt here is my Py4j implementation of `hasCompleteness`:
https://github.com/margitaii/pydeequ/blob/master/src/pydeequ/checks.py#L109

Hope it helps.
