### ISSUE TITLE
Checks where rule is dependent on value of another field with Deequ

### ISSUE THREAD

**Issue by infornite** [awslabs/deequ#110]
I am evaluating some DQ tools and Deequ looks really interesting. However, I can't assess whether or not Deequ support checks on a column where the rule needs to use other columns as an input. Below is a sample dataset to illustrate what I want to achieve.

**Dataset**
Customer Type | First Name | Last Name | Business Name
Individual         | John            | Doe           | Null
Individual         | Jane            | Doe           | Null
Company         |                    |                   | Acme Studios Ltd.

**Objective**
I want to have a rule that states:
IF Customer Type IS Individual THEN First Name SHOULD NOT BE NULL
IF Customer Type IS Individual THEN Last Name SHOULD NOT BE NULL
IF Customer Type IS Company THEN Business Name SHOULD NOT BE NULL

Is this possible with Deequ?

Thanks
Michael

**Comment by sscdotopen** [comment]
Hi Michael,

This is supported via an optional ```where``` clause that you can supply for most constraints, e.g.,

```scala
val verificationResult = VerificationSuite()
  .onData(data)
  .addCheck(
    Check(CheckLevel.Error, "unit testing my data")
      .isComplete("first_name").where("customer_type = 'individual'")
      .isComplete("last_name").where("customer_type = 'individual'")
      .isComplete("business_name").where("customer_type = 'company'")
)
.run()
```

**Comment by infornite** [comment]
Thanks a lot for the clarification
