### ISSUE TITLE
Pyspark version

### ISSUE THREAD

**Issue by mmistroni** [awslabs/deequ#112]
Hi guys
  any plans for a python version that can be used with pyspark>?
kind regards
 Marco

**Comment by TammoR** [comment]
Hi,

We have no concrete plans for pyspark bindings at the moment but would be very happy for contributions. In the meantime, maybe Py4j could be helpful (see also [this issue](https://github.com/awslabs/deequ/issues/109)).

**Comment by mmistroni** [comment]
Thank you. Let me have  a look at the scala codebase.... but don't count on
me yet....
kind regards

**Comment by johnrussell9983** [comment]
+1 for some code to import into Pyspark

**Comment by QKKQQK** [comment]
I posted Issue#109 (Deequ with Py4J and PySpark), but now I'm having trouble initializing function parameters for functions like

`public com.amazon.deequ.checks.CheckWithLastConstraintFilterable hasCompleteness(java.lang.String, scala.Function1<java.lang.Object, java.lang.Object>, scala.Option<java.lang.String>);`
Note: this is part of the javap output for Check.class

I'm having trouble converting a Python function / scala function string into a scala.Function1<java.lang.Object, java.lang.Object>.
