### ISSUE TITLE
Extensible Profiling via custom analyzers

### ISSUE THREAD

**Issue by castorm** [awslabs/deequ#113]
It'd be great if we could extend profiling to take ad-hoc analyzers.

I can think of things like:
- Timeliness analyzer to be configured with even-time column and process-time column.
- Completeness analyzer able to treat custom defaults as NULLs.
- Row Completeness analyzer (as opposed to column completeness).
- etc.

**Comment by sscdotopen** [comment]
Hi Castor,

You can use the [Compliance](https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/Compliance.scala) Analyzer to compute metrics over the data with customizable expressions, hope that would help with your use case.
