### ISSUE TITLE
Clarification around RateOfChangeStrategy

### ISSUE THREAD

**Issue by cvaliente** [awslabs/deequ#114]
according to https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/examples/anomaly_detection_example.md

> We test for anomalies in the size of the data, and want to enforce that it should not increase by more than 2x. We define a check for this by using the RateOfChangeStrategy for detecting anomalies.

This (as well as the name of the strategy) implies that the RateOfChangeStrategy checks for relative changes in the data.
but both the documentation at https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/anomalydetection/RateOfChangeStrategy.scala#L26
as well as the actual implementation 
https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/anomalydetection/RateOfChangeStrategy.scala#L68 and L95f
imply that RateOfChangeStrategy checks for absolute changes. (i.e. the value changes by more than x instead of x%)

Going from the name I would expect the example to be correct and the implementation is wrong (the actual implementation would be something like an AbsoluteChangeStrategy)
This seems like a rather basic thing so I am not sure if I got this completely wrong. I would appreciate someone having a look and clarifying this.

**Comment by sscdotopen** [comment]
Dear Clemens, 

You are absolutely correct, thank you for catching this! Would you have some time to update the example and send us a PR? That would be awesome :)
