### ISSUE TITLE
Can't run checks on nested columns

### ISSUE THREAD

**Issue by yulihav** [awslabs/deequ#118]
How do you access nested columns in the checks? This is my schema:
```
root
 |-- id: string (nullable = true)
 |-- data: struct (nullable = true)
 |    |-- lead: struct (nullable = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- brand: string (nullable = true)
```
but when I add check 
```Check(CheckLevel.Error, "level-2").isComplete("data.lead"))```, 

I get the following failure
```CompletenessConstraint(Completeness(data.lead,None)) failed: Input data does not include column data.lead!```

Even though `data.lead` is populated.

Is there a different approach to verifying nested columns?

**Comment by sscdotopen** [comment]
Dear Yuliana,

We don't support nested data at the moment unfortunately. You would have to manually unnest your data in order to run these checks.

Best,
Sebastian

**Comment by afranzi** [comment]
Hi Sebastian,
I was wondering if there is any strong reason to avoid nested fields support?

Thanks,

**Comment by sscdotopen** [comment]
Hi Albert,

There are two major reasons IMHO:
 * It is difficult to define the semantics of some statistics like completeness or uniqueness, when a field can have an arbitrarily deep nested object with duplicates
 * It also becomes difficult to query nested data efficiently, especially if it contains maps and arrays

**Comment by afranzi** [comment]
It could support statistics on primitive fields. So given the @yulihav  example, it should be easier to support checks on `data.lead.id` as a first iteration. I understand that maybe completeness of an object could need some boundaries to be defined.

Regarding efficiency. it shouldn't be an issue using the predicates down. 
In the end, it would be more about how the developers are using the library. But I believe it would be great and it could get more community adoption if Deequ starts supporting nested fields.

**Comment by sscdotopen** [comment]
I think it would be dangerous to only support nested fields in some cases and for some metrics, as this might be hard to communicate to our users.

**Comment by esil-esil** [comment]
Just FYI: During the very same verification run: 

.containsURL CAN find nested data, whereas most other constraints (in example screenshot .hasDataType) cannot find the exact same nested data. 

![ConstraintsOnNestedData](https://user-images.githubusercontent.com/59602920/73723360-264c7e80-4729-11ea-81d3-da9959494e18.png)
