### ISSUE TITLE
Persistance only for success check in the example shared

### ISSUE THREAD

**Issue by ankit-khare-2015** [awslabs/deequ#119]
Testing the Persistance example .

`deequ/src/main/scala/com/amazon/deequ/examples/metrics_repository_example.md`

It only saves the positive results for e.g if we have failure then it is not saved .

i.e if i change 

`.addCheck(Check(CheckLevel.Error, "integrity checks")
        .hasSize(_ == 5)` to 

`.addCheck(Check(CheckLevel.Error, "integrity checks")
        .hasSize(_ > 10)`

and check the results , it does not display the same in metrics.json

**Comment by sscdotopen** [comment]
Dear Ankit,

Could you be more specific about the issues that you are having? We explicity designed the metrics repository to only store successful check results. We can work on changing that if it helps your use case.

**Comment by ankit-khare-2015** [comment]
Thanks for the response , 

Requirement : Common dataframe that can show below data as mentioned in the case class below 

  case class SimpleCheckResultOutput(table: String,
                                     constraint: String,
                                     constraintStatus: String,
                                     constraintMessage: String,
                                     column: String,
                                     value: String)

with this we we can combine the verification checks with actual metrics also we can enhance the df as well .

`+-------------------+------------------------------------------------------------------------------------------------------------------------+----------------+----------------------------------------------------+------------------------------+-----+----------+
|table              |constraint                                                                                                              |constraintStatus|constraintMessage                                   |column                        |value|sync_day  |
+-------------------+------------------------------------------------------------------------------------------------------------------------+----------------+----------------------------------------------------+------------------------------+-----+----------+
|test-data-1.parquet|ComplianceConstraint(Compliance(numViews is non-negative,COALESCE(numViews, 0.0) >= 0,None))                            |Success         |null                                                |numViews is non-negative      |1.0  |2016-08-04|
`

**Comment by ankit-khare-2015** [comment]
@sscdotopen ,

Let me know if you get the requirement and if you wish i can open an PR if u like the feature . since i guess this will be always have a dataframe with more information rather than only

**Comment by sscdotopen** [comment]
Hi Ankit,

Feel free to post a PR, Im happy to look at it.

**Comment by sscdotopen** [comment]
It would be important to keep some level of backwards compatibility though to not alter the functionality for currently deployed use cases.

**Comment by ankit-khare-2015** [comment]
ya that will make sense , i will open the PR soon ...

**Comment by lange-labs** [comment]
Resolving due to inactivity
