### ISSUE TITLE
DQ Rules across datasets

### ISSUE THREAD

**Issue by infornite** [awslabs/deequ#121]
Hi,

I'm evaluating Deequ and I have a specific question about its capability to test data quality where a rule is dependent on values spread across 2 or more data-sets.

Dataset 1: Accounts
 - ClientId
 - AccountId
 - AccountType

Dataset 2: Clients
 - ClientId
 - ClientType

**Rule to test Accounts.AccountType**
IF Clients.Client Type = "Business"
THEN Accounts.AccountType MUST BE IN ("BUSINESSLOAN", "BUSINESSTRANS")

Is this type of rule where there are dependencies across datasets possible in Deequ?

Thanks
Michael

**Comment by sscdotopen** [comment]
Hi,

At the moment deequ requires all the data to be in a single dataframe. So in your example, you would have to join the two tables first, and afterwards run the check on the join result.
