### ISSUE TITLE
Improvement suggestion for the example files

### ISSUE THREAD

**Issue by sergred** [awslabs/deequ#125]
In the example file ```examples/DataProfilingExample.scala``` and others the toy schema

```scala
case class RawData(name: String, count: String, status: String, valuable: String)
```
includes attributes "name" and "count" that are a bit misleading. Later in the code the line

```scala
val countProfile = result.profiles("count").asInstanceOf[NumericColumnProfile]
```

made it a bit unintuitive to distinguish whether the "count" here is a total-number-of-records statistics of the column profiles, or a column name for this particular toy dataset. Took a while to figure out why this example code crushes with the new data schema.

It would be better to avoid using the attributes that are ambiguous in the context of the example code.

**Comment by sscdotopen** [comment]
Thank you, Sergey, this is a very good find. Would you be able to prepare a PR to fix the example?
