### ISSUE TITLE
Clarification around DynamoDB as a Metrics Repository

### ISSUE THREAD

**Issue by pkrish** [awslabs/deequ#128]
Hi, 
In the paper http://www.vldb.org/pvldb/vol11/p1781-schelter.pdf you mention that DynamoDB is used as the metrics repository (Implementation section) but I can't find it in the code base. 

Do you plan on adding this feature? 

Thanks

**Comment by sscdotopen** [comment]
Dear pkrish,

Such a repository is not part of the current code base, as we do not want to include the dependency to the corresponding AWS libraries in our release. We would be happy to assist you with coding up a dynamodb-backed repository if you want to start working on that.

**Comment by pkrish** [comment]
Makes sense. S3 backed metrics repo should be good for now. I'll look into using Dynamodb if we run into performance issues.
