### ISSUE TITLE
ColumnProfilerRunner - distinct values for non numeric columns

### ISSUE THREAD

**Issue by fmarelli** [awslabs/deequ#129]
Hi

the example

https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/examples/data_profiling_example.md

says "For columns with a low number of distinct values, we collect the full value distribution." Is it possible to override this behaviour so that distinct values are returned if cardinality for the column is less than a specific value? It would also be nice to have an option to return all distinct values without limitations.

Thank you

**Comment by sscdotopen** [comment]
Dear Francesco,

At the moment it is not possible to override this behavior, as this is a performance optimization that allows us to compute histograms for many low-cardinality columns in a single pass over the data.

In general, the size of the result for each column is proportional to the number of distinct values in that columns. If you have a dataset with billions of records and a unique column (e.g., a primary key) than the result would contain billions of records, which will potentially crash the computation.

We could however allow users to increase the cardinality threshold for which we currently compute histograms in https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala#L68

Would that help with your use case?

**Comment by fmarelli** [comment]
Hi, thanks for the prompt reply. Yes, it does help!
