### ISSUE TITLE
ColumnProfilerRunner not writing value to repository

### ISSUE THREAD

**Issue by fmarelli** [awslabs/deequ#131]
Hi

the following code does not generate the metrics.json file in the output directory. I am using a Zeppelin notebook on an AWS EMR cluster

    `
    val metricsFile = new File(Files.createTempDir(), "metrics.json")
    println(metricsFile.getAbsolutePath)
    val repository: MetricsRepository = FileSystemMetricsRepository(spark, metricsFile.getAbsolutePath)
    val keyTag: String = db+"."+table
    val resultKey = ResultKey(System.currentTimeMillis(), Map("tag" -> keyTag))

    val result = ColumnProfilerRunner()
        .onData(tableDF)
        .useRepository(repository)
        .saveOrAppendResult(resultKey)
        .run()
`

Absolute path is /tmp/1566575696531-0/metrics.json. I can see the directory created on the master node, but no json file.

Thank you

**Comment by sscdotopen** [comment]
Hi Francesco, 

I checked your code locally on my notebook and I had a metrics.json written. How exactly does your setup look like? You talk about a master node? The output will be written whereever your spark driver is running, which is not necessarily the master node. 

You can also have the MetricsRepository live on S3 if that helps.

**Comment by sscdotopen** [comment]
You can prefix the file path with file://, hdfs:// or s3n:// to specify exactly where to store the metrics.

**Comment by fmarelli** [comment]
Hi, writing to s3 works fine, thank you.
