### ISSUE TITLE
runOnAggregatedStates with saveStatesWith not persisting all metrics

### ISSUE THREAD

**Issue by romansegador** [awslabs/deequ#135]
I'm trying to persist the state after calculate metrics from already persisted states. 

Functional Scenario is:
- Each day metrics are calculated for the given day and the delta is persisted with HdfsStateProvider
- With AnalysisRunner.runOnAggregatedStates, we calculate the metrics with the states saved as the aggregated until yesterday and the new daily delta. The result is the new total aggregated for tomorrow.

On the second case, when is used the "saveStatesWith" parameter, the state is not persisted (or at least not completely). 
example:
```
val stores: Seq[HdfsStateProvider] = Seq(hdfsStateStoreDay, hdfsStateStoreAggregatedUntilYesterday)

val aggregatedMetrics = AnalysisRunner.runOnAggregatedStates(
            schema= dataFrame.schema,
            analysis = analysis,
            stateLoaders = stores,
            saveStatesWith = Some(hdfsStateStoreAggregated)
          )

```

Digging into the code I've realized that it is only stored for groupingAnalyzers but not for scanningAnalyzers

```
 /* Identify analyzers which require us to group the data */
    val (groupingAnalyzers, scanningAnalyzers) =
      passedAnalyzers.partition { _.isInstanceOf[GroupingAnalyzer[State[_], Metric[_]]] }

    val nonGroupedResults = scanningAnalyzers
      .map { _.asInstanceOf[Analyzer[State[_], Metric[_]]] }
      .flatMap { analyzer =>
        analyzer
          .loadStateAndComputeMetric(aggregatedStates)
          .map { metric => analyzer -> metric }
      }
      .toMap[Analyzer[_, Metric[_]], Metric[_]]


    val groupedResults = if (groupingAnalyzers.isEmpty) {
      AnalyzerContext.empty
    } else {
      groupingAnalyzers
        .map { _.asInstanceOf[GroupingAnalyzer[State[_], Metric[_]]] }
        .groupBy { _.groupingColumns().sorted }
        .map { case (_, analyzersForGrouping) =>

          val state = findStateForParticularGrouping(analyzersForGrouping, aggregatedStates)

          runAnalyzersForParticularGrouping(state, analyzersForGrouping, saveStatesWith,
            storageLevelOfGroupedDataForMultiplePasses)
        }
        .reduce { _ ++ _ }
    }
```

I think it is a bug and should be also saved on this cases but please let me know your feedback. 

Thanks

**Comment by romansegador** [comment]
I will create a pull request with the fix later to be merged if you agree it is a bug.

**Comment by sscdotopen** [comment]
Hi, yes this looks like a bug to me, let me have a look at your PR. Thanks for the find!

**Comment by sscdotopen** [comment]
Thank you for the clarifications, Roman. You found a tricky bug, thanks for that. I created a PR myself, as I was trying to reproduce the issue within some existing tests. Could you have a look at it?

https://github.com/awslabs/deequ/pull/137

**Comment by romansegador** [comment]
Thanks Sebastian, (as expected :)) your code is much clearer and efficient that my pull request. I tried your code with my own examples and works properly.  

Do you think it would be possible to cut a new version with this fix?

Thanks for your quick response.

**Comment by sscdotopen** [comment]
Hi Roman,

I will be traveling the next days, but I can ask a colleague to cut a new release with this fix.

Thank you for your contribution!

**Comment by romansegador** [comment]
That will be great Sebastian.

Thanks
