### ISSUE TITLE
Clarify support for Spark 2.3 and 2.4

### ISSUE THREAD

**Issue by groodt** [awslabs/deequ#139]

**Comment by mesmat** [comment]
I have the same question too; does it support Spark 2.3 and 2.4?

**Comment by sandeepsingh4** [comment]
Yes, I have tested it with Spark 2.3.4 with Scala 2.11.8 and it is working fine. I had a dry run with Spark 2.4.4 and Scala 2.11.11 and it executed successfully, however there is issue with Spark 2.4.4 with Scala 2.11.12 where I am getting number format exception in few cases in my implementation. I have raised a issue with Scala community for the same.(https://github.com/scala/bug/issues/11735)

**Comment by sscdotopen** [comment]
We are testing our release on EMR clusters with Spark 2.3 and 2.4, so deequ should work without problems with these Spark versions. If you run into an issue, don't hesitate to open a ticket here.

**Comment by groodt** [comment]
> We are testing our release on EMR clusters with Spark 2.3 and 2.4, so deequ should work without problems with these Spark versions. If you run into an issue, don't hesitate to open a ticket here.

@sscdotopen If that is indeed the case (I believe it is too), why not accept the PR related to this ticket to update the README to clarify?

**Comment by groodt** [comment]
@sscdotopen The PR is: https://github.com/groodt/deequ/pull/1
