### ISSUE TITLE
ColumnProfilerRunner - lowCardinalityHistogramThreshold - "Other" value

### ISSUE THREAD

**Issue by fmarelli** [awslabs/deequ#141]
Hi

I understand the need to have a the "lowCardinalityHistogramThreshold" parameter for ColumnProfilerRunner, as also discussed in another issue a while ago. It would be very useful, for columns with cardinality that is greater than lowCardinalityHistogramThreshold to have the top values by number of occurrences and ratio per value plus a derived distinct value "Other" that contains the sum of the other values, this way all non numeric columns would have this information populated.

The way it is now it is all or nothing depending on lowCardinalityHistogramThreshold.

Is this something that can be implemented?

Thank You

**Comment by lange-labs** [comment]
Resolving due to inactivity
