### ISSUE TITLE
Ignore case implementation while VerificationSuite Checks.

### ISSUE THREAD

**Issue by sandeepsingh4** [awslabs/deequ#144]
Hello, I came up with a scenario where I am loading data from one source to another and trying to verify the target data-set against its source. Hence, here I am generating the constraints from source and verifying the suggestions on target data-set.

The source column name is in camel case hence the underlined column name is suggested constraints is also same as its source which is correct for example the suggestions are:
```
.isComplete("CreatedBy")
.isComplete("IsDeleted")
```
I am trying to verify these suggestion on the target dataset which column name is in upper case (ISDELETED, CREATEDBY) hence the CompletenessConstraints verification is failing with following error:

```
{"check":"6","check_level":"Error","check_status":"Error","constraint":"CompletenessConstraint(Completeness(IsDeleted,None))","constraint_status":"Failure","constraint_message":"Input data does not include column IsDeleted!"}

{"check":"5","check_level":"Error","check_status":"Error","constraint":"CompletenessConstraint(Completeness(CreatedBy,None))","constraint_status":"Failure","constraint_message":"Input data does not include column CreatedBy!"}
```
I feel that the column name in the constraints suggestion should not be case sensitive and VerificationSuite Checks should ignore case while verification and support all provided type during the verification.

**Comment by sscdotopen** [comment]
Hi Sandeep,

Thank you for bringing up this issue. I did some googling and I came across some articles and posts that mentioned that different data stores and formats like Hive or Parquet handle case sensitivity in column names differently. I would rather not have deequ enforce some behavior here.

If you want to get rid of case sensitivity for your use case, you can just rename the fields of your dataframe before you run the verification with deequ. I hope that answers your question.

**Comment by sandeepsingh4** [comment]
Hi Sebastian,
Thanks for your reference. I am currently doing the same and converting the column name in Upper case while passing it in verification run. In Hive point of view,  It looks like hive ignoring the case and considering all details in lower case. Please see the response from different scenarios from Hive.

```
0: jdbc:hive2://myhost.myorg.com:> create table test_CASE (Name String, AGE int, Address String) STORED AS PARQUET;
No rows affected (0.365 seconds)
0: jdbc:hive2://myhost.myorg.com:> desc test_CASE;
+-----------+------------+----------+--+
| col_name  | data_type  | comment  |
+-----------+------------+----------+--+
| name      | string     |          |
| age       | int        |          |
| address   | string     |          |
+-----------+------------+----------+--+
3 rows selected (0.429 seconds)


Scenario 2:

0: jdbc:hive2://myhost.myorg.com:> create table test_CASE_1 (NAME String, AGE int, ADDRESS String) STORED AS PARQUET;
No rows affected (0.379 seconds)
0: jdbc:hive2://myhost.myorg.com:> desc test_CASE_1;
+-----------+------------+----------+--+
| col_name  | data_type  | comment  |
+-----------+------------+----------+--+
| name      | string     |          |
| age       | int        |          |
| address   | string     |          |
+-----------+------------+----------+--+
3 rows selected (0.399 seconds)


0: jdbc:hive2://myhost.myorg.com:> select NAME, age from test_case;
+-------+------+--+
| name  | age  |
+-------+------+--+
+-------+------+--+
No rows selected (0.193 seconds)
```

**Comment by sscdotopen** [comment]
Hi Sandeep, 

I am not sure whether Deequ is the right place to fix such problems. I think Deequ should work with the original column names provided in the DataFrame, and throw errors if a constraint does not match the column names.

We internally rely on Spark schemas (via StructType) to resolve field names. Spark's implementation will throw exception if the name is not in correct capitals, e.g., this code results in the following  `java.lang.IllegalArgumentException: Field "NAME" does not exist.`

```
  val schema = StructType(
    StructField("name", IntegerType) :: Nil
  )

  println(schema("NAME"))
```
