### ISSUE TITLE
address validation

### ISSUE THREAD

**Issue by fatangare** [awslabs/deequ#147]
Hi,

How can I do address validation using deequ e.g. to check if address column has correct address?

Regards,
Sandeep

**Comment by sscdotopen** [comment]
Hi Sandeep,

What does it exactly mean for you that an address is correct? Does it mean that the string adheres to some kind of syntax or does it mean that the address matches some other address in a database?

If you want to do syntax validation and can express the validation logic in SQL (e.g. as a regex), you can use ```Check.satisfies ```

https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/checks/Check.scala#L571

**Comment by fatangare** [comment]
Thanks. It will be regex. I will try using `Check.satisfies`
