### ISSUE TITLE
Row level completess

### ISSUE THREAD

**Issue by rambrus** [awslabs/deequ#148]
Hi Team,

We have a use case where we want to collect the following metrics:
_the proportion of rows which contain at least 1 null/missing value_

Do you have any suggestion to cover this use case using *deequ*? 

I have workaround idea:
- add a new `boolean` column (e.g. `has_null`) to the input DataFrame that is indicating whether we have any null / missing value in the given row
- use `Compliance("has_null == true")` analyzer

Is there a better solution to this? Maybe I could write a dynamic predicate for Compliance that iterates all the columns and checks if any of them null.

Thanks in advance,
Robert

**Comment by sscdotopen** [comment]
Hi Robert,

You could generate a SQL predicate like "(column_a IS NULL) OR (column_b IS NULL) OR (column_c IS NULL)" containing all your columns and create a constraint for it with`Check.satisfies`

**Comment by rambrus** [comment]
Cool, thanks for the hint, will give it a try!

**Comment by rambrus** [comment]
Tested your suggestion, working fine, closing this thread!
Thanks

**Comment by rambrus** [comment]
Yeah, I think it makes sense to add it a more generic way. It might be useful to provide the ability to specify a list of columns to be analyzed, instead of including all columns by default.
What do you think?

I will take a look at the API and come up with a proposal.

**Comment by sscdotopen** [comment]
I think it would make for a good default to test all columns, but the check should also provide an option to restrict the columns which cannot be null.

**Comment by rambrus** [comment]
Makes sense

**Comment by rambrus** [comment]
Feature implemented, see the above PR
