### ISSUE TITLE
Grouped metrics

### ISSUE THREAD

**Issue by rambrus** [awslabs/deequ#149]
Hi Team,

We have a use case where we want to collect some metrics for a grouped DataFrame, we want to see the collected metrics (e.g. Completeness, ApproxQuantiles, Histogram) separately for every group.
We also want to store the metrics in MetricsRepository.
Any best practices on this?

*I have the following idea:*
- filter a group of the DataFrame, pass it to *deequ* for analyis
- store the metrics in MetricsRepository, using the group value as a tag 
- repeat the above steps for every group

It might be working, but it's pretty time-consuming. Any idea to improve this approach?

Thanks in advance,
Robert

**Comment by sscdotopen** [comment]
Unfortunately, we don't have a good idea how to do this in general, because the number of groups might be very large if you have a large number of distinct values in the field by which you group.

If you know the number of groups in advance, then you can do some workaround by generating a constraint per group with our where filter like this:

```
Check(CheckLevel.Warning, "")
 .isComplete("column_of_interest").where("column_to_group_on = 'groupA'") 
 .isComplete("column_of_interest").where("column_to_group_on = 'groupB'") 
 .isComplete("column_of_interest").where("column_to_group_on = 'groupC'") 
```

However this requires you to know the groups in advance. An advantage is that this does not require shuffling the data and runs in a single pass.

**Comment by rambrus** [comment]
Yeah, I've seen this option, but found that `where` filter is only supported in some Checks (e.g. `hasSize`, `hasCompleteness`)

As I understand, many Checks do not support this feature, e.g.
[ApproxQuantiles](https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/ApproxQuantiles.scala)

In my understanding this example is invalid:
```
Check(CheckLevel.Warning, "")
  .hasApproxQuantile("numViews", 0.5, _ <= 10).where("column_to_group_on = 'groupA'")
  .hasApproxQuantile("numViews", 0.5, _ <= 5).where("column_to_group_on = 'groupB'")
  .hasApproxQuantile("numViews", 0.5, _ <= 1).where("column_to_group_on = 'groupC'")
```

I assume the `Check` needs to be an instance of `CheckWithLastConstraintFilterable` to be able to use `where`. Is that correct?

**Comment by sscdotopen** [comment]
Yes, your understanding is right. I am not sure why ApproxQuantiles does not support this, it should be possible IMHO.

**Comment by rambrus** [comment]
hmm, actually it seems about half of the checks do not support this filtering:
```

+------------------------------+-----------------------------------+
|            check             |            return_type            |
+------------------------------+-----------------------------------+
| addConstraint                | Check                             |
| isUnique                     | Check                             |
| isPrimaryKey                 | Check                             |
| hasUniqueness                | Check                             |
| hasDistinctness              | Check                             |
| hasUniqueValueRatio          | Check                             |
| hasNumberOfDistinctValues    | Check                             |
| hasHistogramValues           | Check                             |
| hasEntropy                   | Check                             |
| hasMutualInformation         | Check                             |
| hasApproxQuantile            | Check                             |
| hasMean                      | Check                             |
| hasPattern                   | Check                             |
| containsCreditCardNumber     | Check                             |
| containsEmail                | Check                             |
| containsURL                  | Check                             |
| containsSocialSecurityNumber | Check                             |
| hasDataType                  | Check                             |
| hasSize                      | CheckWithLastConstraintFilterable |
| isComplete                   | CheckWithLastConstraintFilterable |
| hasCompleteness              | CheckWithLastConstraintFilterable |
| hasMinLength                 | CheckWithLastConstraintFilterable |
| hasMaxLength                 | CheckWithLastConstraintFilterable |
| hasMin                       | CheckWithLastConstraintFilterable |
| hasMax                       | CheckWithLastConstraintFilterable |
| hasSum                       | CheckWithLastConstraintFilterable |
| hasStandardDeviation         | CheckWithLastConstraintFilterable |
| hasApproxCountDistinct       | CheckWithLastConstraintFilterable |
| hasCorrelation               | CheckWithLastConstraintFilterable |
| satisfies                    | CheckWithLastConstraintFilterable |
| isNonNegative                | CheckWithLastConstraintFilterable |
| isPositive                   | CheckWithLastConstraintFilterable |
| isLessThan                   | CheckWithLastConstraintFilterable |
| isLessThanOrEqualTo          | CheckWithLastConstraintFilterable |
| isGreaterThan                | CheckWithLastConstraintFilterable |
| isGreaterThanOrEqualTo       | CheckWithLastConstraintFilterable |
| isContainedIn                | CheckWithLastConstraintFilterable |
+------------------------------+-----------------------------------+
```

Can someone please clarify the reason?

**Comment by sscdotopen** [comment]
You are raising a valid point, I think the filtering could be implement for most of them.

**Comment by sscdotopen** [comment]
Would you be interested in working on a PR for this issue? I'd be happy to guide you through the code.

**Comment by rambrus** [comment]
I'm interested, clarifying the open source contribution process with my company and will get back to you soon.

**Comment by rambrus** [comment]
Ok, updated my account to be compliant with the company standards, also forked the repo, cloned and run the unit tests. All looks good.

**Comment by esil-esil** [comment]
Will where filter also be implemented for the following 5 constraints? 

.hasPattern
.containsEmail
.containsURL
.containsSocialSecurityNumber
.hasDataType

E.g. I would like to be able to specify the check below, as I have rows of different profileTypes, and only profileType 'personal' has an email (in which case I would like to verify the email).

.addCheck(Check(CheckLevel.Error, "Error").containsEmail("personal.email").where("profileType = 'personal'"))

Thank you very much in advance for your contribution and answer.

**Comment by rambrus** [comment]
@esil-esil yes, the plan is to make `where` statement available for all these constraints. it should not be a huge effort in my opinion, just haven't had time to focus on this due to other priorities.

**Comment by esil-esil** [comment]
@rambrus : looking very much forward to your contribution.
I am software tester, not developer, so unfortunately I cannot contribute myself.

**Comment by rambrus** [comment]
All the Checks have been refactored to support filtering, closing this ticket.

**Comment by esil-esil** [comment]
@rambrus Fantastic! Thank you very much :-)

**Comment by voducvan** [comment]
hi @rambrus , 
Do you know if it's possible to run the Analyzer with grouping condition as well ? 
i.e: Our use case is we have dataset updated daily and we wanna see "Uniqueness" or Distinctness metrics grouped by Date. 
I knows I can do adding the "filter condition" for each date but actually it results in unnecessary run while we can run it in 1 turn.

**Comment by rambrus** [comment]
@voducvan So, you want to group your data by date and collect the `Uniqueness` and `Distinctness` metrics for each group in one go, right?

**Comment by voducvan** [comment]
@rambrus : yes, Do you have any recommendation using the AnalysisRunner, ?

**Comment by rambrus** [comment]
I don't think it's supported at the moment.

@sscdotopen do you have a suggestion?

**Comment by sscdotopen** [comment]
There are two options:

(1) If you know all the values of the column to group by upfront, you can just use .where("") to filter for each one and run lots of checks.
(2) Otherwise, you can manually filter the dataframe before passing it to Deequ, however this will result in many jobs being produced

**Comment by gauravbrills** [comment]
> There are two options:
> 
> (1) If you know all the values of the column to group by upfront, you can just use .where("") to filter for each one and run lots of checks.
> (2) Otherwise, you can manually filter the dataframe before passing it to Deequ, however this will result in many jobs being produced
@sscdotopen 
option 2 is a good workaround but cant we just give the ability to group based on columns and then do a stat over it like sum max similar to a partition query ..  **where**  could be used in addition to this to do extra filtering. Should this not be supported OOB not sure the complexity here for deequ
