### ISSUE TITLE
Feature Request: Scope of "constraints" variable in Check case class 

### ISSUE THREAD

**Issue by joshivinay** [awslabs/deequ#150]
Is it possible to remove the "private[deequ]" scope on the constraints field in the Check case class? I would like to extend Check in my own project and with the private[deequ] on the constraints its not possible.

**Comment by sscdotopen** [comment]
Hi Vinay,

We are very reluctant to remove this scope, as we do in general not support extension of these checks. If you want to write your own checks, you can simply use `com.amazon.deequ` as package of your code. In scala you can just use this at the top of your source code file.

We for example use this trick to extend certain internals of Spark https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/catalyst/StatefulDataType.scala

**Comment by joshivinay** [comment]
Gotcha! 
Unfortunately, my organization will not allow me to use com.amazon.deequ as the package name unless the deequ license allows me to do so. Will the current deequ license allow me to do so within my project source code?

**Comment by sscdotopen** [comment]
The code is under Apache license, so I don't think that there is a problem here.
