### ISSUE TITLE
allowOverwrite = True for HdfsStateProvider complains with isUnique Constraint Check

### ISSUE THREAD

**Issue by singhrajk** [awslabs/deequ#151]
Hey Team, 
If I do a **isUnique** Constraint Check and try to store the state in a HDFSStateProvider. Rerun fails even with **allowOverwrite = True**. That's because there is no check for **allowOverwrite** while writing the state frequencies in parquet in the **persistDataframeLongState** method. 

Suggested Solution -> Do a check of the flag. If true, do a df.write.parquet in overwrite mode. 

P.S. - Would love to work on a PR.

**Comment by sscdotopen** [comment]
Thank you for catching that. We would be glad to receive a PR from you!
