### ISSUE TITLE
Is there any way to persist the table profile results as Dataframe 

### ISSUE THREAD

**Issue by jumpnrun88** [awslabs/deequ#154]
Hello Everyone , 

I would like to know  how we can persist the table profile results as data frame/ json format  , Currently  the return  type is a scala object ColumnProfilerRunner Type , 
Anyone implemented this scenario  ? 

thank you .

**Comment by sscdotopen** [comment]
Hi, 
Sorry for not answering earlier, I must have overlooked this issue. You can configure the ColumnProfiler to store results in a `MetricsRepository` via `useRepository`. Then you can retrieve the resulting metrics in json or dataframe format afterwards.

**Comment by cvaliente** [comment]
for a quick conversion you can do
`ColumnProfiles.toJson(result.profiles.values)`
