### ISSUE TITLE
Cross-column map check.

### ISSUE THREAD

**Issue by dKiwi** [awslabs/deequ#155]
Hi,

Is there currently a way to verify whether two fields comply with a key-value constraint?

Example - if the country is "US" the region  should always be "North America". 

I guess we can always calculate the levels of correlation or mutual information but that's not quite the same as complying with a specific set of mapping rules.

**Comment by sscdotopen** [comment]
Something along the lines of

```
Check.satisfies("region = 'North America'").where("country = 'US'")
```

should work here.
