### ISSUE TITLE
Anomaly Detection

### ISSUE THREAD

**Issue by nitin-rastogi** [awslabs/deequ#156]
I want to compare average sizes of last three or x months with current month. How can I do it?

**Comment by sscdotopen** [comment]
Hi Nitin,

We have a [tutorial](https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/examples/anomaly_detection_example.md) explains how to setup the anomaly detection with deequ in general.

You can choose from different [algorithms](https://github.com/awslabs/deequ/tree/master/src/main/scala/com/amazon/deequ/anomalydetection
) for anomaly detection. 

The one that is closest to your use case is probably the [OnlineNormalStrategy](https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/anomalydetection/OnlineNormalStrategy.scala), which computes a running mean of the statistic and allows to specify how many standard deviations a value must be away from the mean to be flagged as an anomaly.

**Comment by nitin-rastogi** [comment]
Thanks. I will try it

**Comment by nitin-rastogi** [comment]
It worked really nicely. Thanks for help.
