### ISSUE TITLE
Anomaly Detection on keys

### ISSUE THREAD

**Issue by breathe1988** [awslabs/deequ#158]
Hi Team,

I have been trying to understand if it is possible to implement your anomlay detection strategy not only on the full dataset but on the multiple subset.

Example: I have 150 warehouse generating data in my dataset (wharehouse_id being a column), and I want to apply BatchNormalStrategy for all these particular warehouses.

Can I achieve this ?

**Comment by sscdotopen** [comment]
Hi,

You would have to find a way to compute the metrics for all the groups in your data, which is not directly supported by deequ at the moment.

However if you know the grouping keys (the warehouse ids) beforehand, you could generate a test that looks like

```scala
val yesterdaysKey = ResultKey(System.currentTimeMillis() - 24 * 60 * 1000)

VerificationSuite()
  .onData(yesterdaysDataset)
  .useRepository(metricsRepository)
  .saveOrAppendResult(yesterdaysKey)
  .addAnomalyCheck(
    BatchNormalStrategy(), 
    Size(where=Some("warehouse_id = 0")))
  .addAnomalyCheck(
    BatchNormalStrategy(), 
    Size(where=Some("warehouse_id = 1")))
...
  .addAnomalyCheck(
    BatchNormalStrategy(), 
    Size(where=Some("warehouse_id = 150")))
  .run()
```

Let me know if that helps!

**Comment by lange-labs** [comment]
Resolving due to inactivity
