### ISSUE TITLE
Uniqueness check clarified.

### ISSUE THREAD

**Issue by dKiwi** [awslabs/deequ#160]
Hi Team,

I would like to ask about the hasUniqueness() method.
I understand it is expected to work on multiple columns. What baffles me is a result of the following:

```
val verificationResult = VerificationSuite()
      .onData(df)
        .addCheck(Check(CheckLevel.Error, "test")
                 .hasUniqueness(Seq("Id"), Check.IsOne)
                 .hasUniqueness(Seq("Id", "Address"), Check.IsOne))
      .run()

```

constraint | constraint_status | constraint_message
UniquenessConstraint(Uniqueness(List(Id))) | Success |  
UniquenessConstraint(Uniqueness(List(Id,   Address))) | Failure | Value: 0.2872994429180771 does not meet the constraint requirement!

If the first component of a composite key is unique I would expect all combinations of columns including that component to be unique too. Or is this not how hasUniqueness() is expected to work?

Thanks
Dawid

**Comment by sscdotopen** [comment]
This sounds like a bug. Would you be able to provide us with some data on which you see this happen?

**Comment by dKiwi** [comment]
Sadly not. It's my employer's property.

**Comment by sscdotopen** [comment]
I tested this issue locally and deequ returned the correct result (saying that the combination of columns is unique as well). Can you give us more details about your use case and data?
