### ISSUE TITLE
String hasDataType Check Fails

### ISSUE THREAD

**Issue by Yash0270** [awslabs/deequ#161]
For "hasDataType" check in AnalysisBasedConstraint. 
If the columns contain numbers saved as strings. The check fails.

For ex: 

123Abs == Check Passed
123434 == Check Failed
Asdasd == Check Passed

It must accept just numbers as String, right ??

**Comment by sscdotopen** [comment]
Hi Yash,

Could you post the exact code (and data) which you used to define the test? Its difficult for me to exactly understand the problem from your description.

The datatype check would identify a column of numbers in string representation as numeric, not as string, is that what you are talking about?

**Comment by Yash0270** [comment]
`The datatype check would identify a column of numbers in string representation as numeric, not as string, is that what you are talking about?`

I think we both are on the same page.

For example. 
I have a dataset with schema

Test
 |-- fsn: string (nullable = true)

And my dataset looks like 
**fsn**
123
234

.hasDataType() check fails for **fsn** column for String type 

Shouldn't the numeric values be considered in String ? 
A string can be just made up of digits, digits and alphabets and just alphabets.

My Java code 
```
baseCheck
            .hasDataType(colName, colDataType,
                func(size -> (double) size == 1.0), 
                Option.apply("Datatype check failed for col: " + colName + " for datatype: " + colDataType));
```

**Comment by sscdotopen** [comment]
You are basically, right, however the semantics of Deequ's datatype check are different. It does not check the actual data type used by Spark in the DataFrame, but it will look into String columns and see if the data could be safely casted into another type. It will always report the most specialized type.

If you want to check the datatype that the DataFrame is using, you don't need deequ, you can just call some methods on the DataFrame.

Hope that clarifies things.

**Comment by BabjiManikandanLogandaRajaramKrishnan** [comment]
Hi @sscdotopen, but hasDataType doesn't help us in DATA_TYPE check.

For example :  Consider a column having Zip Code value. Zip Code datatype varies for different Regions (11AN2Z - AlphaNumeric for Americas, 654321 - India) but most of us hold this in String datatype.

Can you please make the dataType cast based on dataFrame.schema instead of typecast to closest match
