### ISSUE TITLE
Using ColumnProfiler on a partitioned table

### ISSUE THREAD

**Issue by yousefzadeh** [awslabs/deequ#163]
Hi
I'm using `ColumnProfilerRunner` on some very large tables that are partitioned by `date` and get updated daily. I'd like to use the `HdfsStateProvider` to store the state for each partition and only analyze the new partitions once when they are written, but it seems to only work with `AnalysisRunner` . Are there any ways to do the similar thing with `ColumnProfilerRunner` ?

Thanks,
Reza

**Comment by sscdotopen** [comment]
Hi Yousef,

This is not directly possible with `ColumnProfileRunner`'s API unfortunately, we assumed that it is used as a one-off solution and not run regularly. 

However,  `ColumnProfileRunner` internally uses  `AnalysisRunner` by conducting three passes over the data with analyzers tailored for the dataset at hand. You could take this code and adjust it for your usecase:

https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala#L90

Let me know if you need more pointers, I'm happy to help.

Best,
Sebastian

**Comment by yousefzadeh** [comment]
Hi Sebastian
Thanks for the quick response, I'll give it a try.

Cheers,
Reza
