### ISSUE TITLE
Content validation possibility

### ISSUE THREAD

**Issue by sandeepsingh4** [awslabs/deequ#167]
Hello,
Could you please help with the content validation possibility using deequ?

Use Case 1: I am moving data from one source to another and wanted to validate certain rows against its target. Is there any constraints available for such validation? If yes, could you please help with the constraints name and how it works. 

Use Case 2: I want to validate records based on certain condition. Can we validate the data using deequ with user defined condition?

**Comment by sscdotopen** [comment]
Hi Sandeep,

I hope I understand your questions correctly.

1) Deequ usually computes aggregate statistics of your data, so you can validate some aggregate stastistics between the two data sources, but Deequ does not support row-level comparisons.

2) What exactly do you mean with a "user defined condition"? Deequ supports a fixed set of metrics to compute over the data, but the validation functions (which decide whether the metric is ok) can be defined by you using arbitrary Scala code.

**Comment by sandeepsingh4** [comment]
Hi Sebastian,
thanks for your answer. User defined condition is like a "user want to validate certain records for a table". 

Since deequ computes the aggregate statistics and supports fixed set of metrics, we can say that data is ok if the stats are matching and it cannot be possible to validate the specific records using deequ .Please correct me if my understanding is incorrect here.

**Comment by sscdotopen** [comment]
Your understanding is correct

**Comment by sandeepsingh4** [comment]
Thanks Sebastian.
