### ISSUE TITLE
Metrics Naming for ApproxQuantile are not clear 

### ISSUE THREAD

**Issue by romansegador** [awslabs/deequ#168]
Hi,

Trying to calculate a few quantiles, I've realised that the metric names are not clear.

If they are calculated individually:
```
ApproxQuantiles("fieldName", Seq(0.25), 0)
ApproxQuantiles("fieldName", Seq(0.5), 0)
ApproxQuantiles("fieldName", Seq(0.75), 0)
```

they end with three metrics with the same name and no clue about the quantile calculated:
```
DoubleMetric(Column,ApproxQuantile,fieldName,Success(0.0))
DoubleMetric(Column,ApproxQuantile,fieldName,Success(12.0))
DoubleMetric(Column,ApproxQuantile,fieldName,Success(30.0))
```

When they are calculated all at once:
```
ApproxQuantiles("fieldName", Seq(0.25, 0.5, 0.75),0)
```
the KeyedDoubleMetric is generated with all the information:
```
KeyedDoubleMetric(Column,ApproxQuantiles,fieldName,Success(Map(0.25 -> 0.0, 0.5 -> 12.0, 0.75 -> 30.0)))
```
Here, the problem is when the KeyedDoubleMetric is flattened in order to process the metrics individually. It ends with three metrics where the calculated quantile is displayed but there is not clue about the metric itself (approxQuantile):
```
DoubleMetric(Column,name-0.25,fieldName,Success(0.0))
DoubleMetric(Column,name-0.5,fieldName,Success(12.0))
DoubleMetric(Column,name-0.75,fieldName,Success(30.0))
```

My Suggestions are:

- At ApproxQuantile, when saving the metric, add the quantile. It is, from `"ApproxQuantile"` to `s"approxQuantile-$quantile"`

- At Metric / KeyedDoubleMetric, on the flatten method, update the instance value from
`s"name-$key` to `s"$name-$key` (actually, I think this is the original expected behaviour).

I'm open to help on the changes if you agree with them.

**Comment by sscdotopen** [comment]
Hi Roman,
Thank you for finding these issues. I agree with your analysis and would be happy to see address in them in a PR!

**Comment by romansegador** [comment]
Pull request created, let me know if something needs to be changed.

**Comment by romansegador** [comment]
@sscdotopen thanks for merge it. When do you think a new version will be released?

**Comment by iamsteps** [comment]
Hi Roman, we are planning to release a new version early next week

**Comment by romansegador** [comment]
Hi @iamsteps, any update on the new version? Thanks in advance

**Comment by iamsteps** [comment]
Hi @romansegador, apologies for the delay. We have created a pre-release, 1.0.3-rc1. We didn't do a full release yet, as we are investigating performance impact of the latest functionality enhancements. Thanks for your patience.

**Comment by lange-labs** [comment]
Resolving per #169 + inactivity
