### ISSUE TITLE
Add support for date types to analyzers like Minimum, Maximum, and Histogram

### ISSUE THREAD

**Issue by andikbui** [awslabs/deequ#170]

**Comment by sscdotopen** [comment]
Yes, that is a very good point. Would you like to help with that?

**Comment by andikbui** [comment]
I am fairly new to Scala and could use some guidance, but I am interested!

**Comment by sscdotopen** [comment]
A problem here is that most of our analyzers end up computing a `DoubleMetric`, e.g., a single floating point number. This will be difficult for dates.

**Comment by klangner** [comment]
What you think of implementing Maximum and Minimum for any 'Comparable` type?
I would be interested in implementing it this way.
It won't work for histogram though.

**Comment by sscdotopen** [comment]
I think this is a duplicate of #47. I agree that it does not make sense to implement this for histograms.
