### ISSUE TITLE
It takes an endless time to download dependencies 

### ISSUE THREAD

**Issue by ravimadhu3** [awslabs/deequ#175]
Just cloned the repo, trying to explore deequ. Opened it in Intellij - and the maven 'Sync' is just spinning. Did this a few times with different connections - still same result. 

![Screen Shot 2019-12-06 at 12 28 03 PM](https://user-images.githubusercontent.com/28542212/70342918-fe719500-1823-11ea-97f4-a3a732c880e7.png)

**Comment by sscdotopen** [comment]
Hi ravimadu3,

This seems to be either a problem of your network connection or of Intellij. Can you try to build deequ via the commandline with `mvn -DskipTests clean install` ?

**Comment by ravimadhu3** [comment]
Cool! That worked - I guess the tests were holding everything up.

**Comment by ravimadhu3** [comment]
Thanks!
