### ISSUE TITLE
Where clause is not indicated in success metrics

### ISSUE THREAD

**Issue by rambrus** [awslabs/deequ#177]
When I have a `VerificationSuite` with a `Check` like this:
```
      .addCheck(Check(CheckLevel.Error, "Sample check")
        .hasSize(_ > 10000).where("entity = 'A'")
        .hasSize(_ > 100000).where("entity = 'B'")
        .hasSize(_ > 100000).where("entity = 'C'")
      )
```

Run the suite and get the `VerificationResult` like this:
```
VerificationResult.successMetricsAsDataFrame(spark, distributionSuite).show()
```

I get back the following result:
```
+-------+--------+----+--------+
| entity|instance|name|   value|
+-------+--------+----+--------+
|Dataset|       *|Size|  5632.0|
|Dataset|       *|Size|422312.0|
|Dataset|       *|Size|126984.0|
+-------+--------+----+--------+
```

It's hard to differentiate these metrics. Is there any chance to add any description / name to the metrics? 
Have seen there is an `hint: Option[String]` param for the constraints, however if understand correctly it's not available in *Metrics* result. 

Adjusting the `name` column might be an option, like this:
```

+---------+----------+----------------------------+----------+
| entity  | instance |            name            |  value   |
+---------+----------+----------------------------+----------+
| Dataset | *        | Size (where: entity = 'A') |   5632.0 |
| Dataset | *        | Size (where: entity = 'B') | 422312.0 |
| Dataset | *        | Size (where: entity = 'C') | 126984.0 |
+---------+----------+----------------------------+----------+
```

Would it be possible to add this info to make the results more clear?

**Comment by sscdotopen** [comment]
Yes, would you like to take a shot a potential implementation?

**Comment by rambrus** [comment]
Yeah, I had a quick look at the source code and found that `Analyzer` name is defined like this:
https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/Size.scala#L37

I assume we can replace the `"Size"` with a function call that includes `where` statement, like this:
```
case class Size(where: Option[String] = None)
  extends StandardScanShareableAnalyzer[NumMatches](composeName("Size", where), "*", Entity.Dataset)
```

The downside: this is not a common approach, need to be done in every `Analyzer` implementation.

Is there any better approach? Can we cover this another layer?

**Comment by sscdotopen** [comment]
Yes, there is some special code that creates the DataFrame outputs, that would be a more appropriate place

**Comment by rambrus** [comment]
Yeah, that makes sense.

I guess this one:
https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/runners/AnalyzerContext.scala#L78

However, I'm not sure if we can retrieve the value of the `where` statement here. Can we access that info somehow?

**Comment by sscdotopen** [comment]
This is the right place. I guess you would have to use reflection to see whether a `where' field exists on the Analyzer object.

**Comment by rambrus** [comment]
That's a good idea, thanks for the hint! I will take a look and get back to you with a pull request.

**Comment by esil-esil** [comment]
Will where filter also be implemented for the following 5 constraints? 

.hasPattern
.containsEmail
.containsURL
.containsSocialSecurityNumber
.hasDataType

E.g. I would like to be able to specify the check below, as I have rows of different profileTypes, and only profileType 'personal' has an email (in which case I would like to verify the email).

.addCheck(Check(CheckLevel.Error, "Error").containsEmail("personal.email").where("profileType = 'personal'"))

Thank you very much in advance for your contribution and answer.

**Comment by rambrus** [comment]
Changes added, see the above PR for details

**Comment by esil-esil** [comment]
I am a little confused ...

In the 1st post of this thread, .hasSize of VerificationSuite is mentioned, but the output format mentioned (columns: entity, instance, name, value) to me appears to be the default output columns of AnalysisRunner, not of VerificationSuite (default output columns: check, check_level, check_status, constraint, constraint_status, constraint_message).

I am using library com.amazon.deequ:deequ:1.0.3-RC1, and have created a similar constraint check .hasSize on 3 different types of data, but I do not get columns 'entity, instance, name, value' as output, but columns 'check, check_level, check_status, constraint, constraint_status, constraint_message', i.e. I do not get a size count for each type, but only constraint_status (Success/Failure) for .hasSize for each type.

Did I misunderstand something?

**Comment by sscdotopen** [comment]
VerificationSuite internally calls AnalysisRunner, so there should not be a difference in the output AFAIK. Size is a bit special because it refers to the dataset as a whole and not to a particular column.

**Comment by esil-esil** [comment]
... your note just hinted me ... explanation is that I use
VerificationResult.checkResultsAsDataFrame instead of 
VerificationResult.successMetricsAsDataFrame

Sorry for the confusion, and thank you very much for a prompt response!

**Comment by sscdotopen** [comment]
You are welcome!
