### ISSUE TITLE
Multi-Column uniqueness/distinctness - not working as expected

### ISSUE THREAD

**Issue by nuarc** [awslabs/deequ#178]
Hi, 
We have a case to find uniqueness by combining multiple columns Example: in Address data, each column could have duplicates but it is not expected to have duplicates if we consider required address sub-fields as shown in example below.

`.hasUniqueness(Seq("Address Line 1","Address Line 2","Address Line 3" ,"City", "Postal Code" , "Country"), Check.IsOne)`

I have applied above checks considering multiple columns, however even though data is unique ( containing nulls in some values), but above results turned out to be < 1.0. 

Executing over say even single col 'Address Line 1' is coming out to be 1.0. 

Could you please help how should i apply this check? And what is the significance or real use-case of sending multi-cols to uniqueness ...

**Comment by sscdotopen** [comment]
Hi nuarc,

If "Address Line 1" does not contain duplicates, then any combination of columns containing it should also not contain duplicates, so something is wrong here. Can you share the data for me to debug what's happening?

**Comment by nuarc** [comment]
Hi Seb, 
Appreciate your prompt response, 
Pls find below additional information:

> 

    qualityChecks += Check(CheckLevel.Error, "Data Validations IN")
      .isComplete("Employee ID")
      .isComplete("Country")
      .isComplete("City")
      .isComplete("Address Line 1")
      .isComplete("Postal Code")
      .hasPattern("Address Line 1", """\d{1,4}.?\s[a-zA-Z\s]{1,30}""".r)
      .isUnique("Address Line 1")
      .isContainedIn("Employee ID", 21000, 22000, includeLowerBound = true, includeUpperBound = true)
      .hasDistinctness(Seq("Address Line 1","Address Line 2","Address Line 3" ,"City", "Postal Code" , "Country"),_ == 1.0)
      .hasUniqueness(Seq("Address Line 1","Address Line 2","Address Line 3" ,"City", "Postal Code" , "Country"), Check.IsOne)

> 

**Sample data: Only share few columns due to PII **


Country | Address Line 1 | Address Line 2 | Address Line 3
-- | -- | -- | --
India | Xavier House, 2nd Floor | St. Peter Colony, Perry Road | Bandra (West)
India | 503 Godavari | Sir Pochkhanwala Road | Worli
India | 4/4 Seema Society | N Dutta Road, Four Bungalows | Andheri
India | 1001D Abhishek Apartments | Juhu Versova Road | Andheri
India | 95, Hill Road |   |  
India | 90 Cuffe Parade | Taj President Hotel | Cuffe Parade
India | 4, Seven PM | Sir Pochkhanwala Rd | Worli
India | 1453 Sahar Road |   |  





**Outcome of metrics as dataframe:**

+-----------+--------------------+------------+-----+
|     entity|            instance|        name|value|
+-----------+--------------------+------------+-----+
|     Column|Employee ID betwe...|  Compliance|  1.0|
|     Column|         Employee ID|Completeness|  1.0|
|     Column|                City|Completeness|  1.0|
|     Column|      Address Line 1|Completeness|  1.0|
|    Dataset|                   *|        Size|  8.0|
|     Column|             Country|Completeness|  1.0|
|     Column|         Postal Code|Completeness|  1.0|
**|Mutlicolumn|Address Line 1,Ad...|  Uniqueness| 0.75|
|Mutlicolumn|Address Line 1,Ad...|Distinctness| 0.75|
|     Column|      Address Line 1|  Uniqueness|  1.0|**
|     Column|      Address Line 1|PatternMatch|0.875|
+-----------+--------------------+------------+-----+

as you can notice, 0.75 on multicol whilst Address Line 1 in itself is unique at 1.0

**Comment by sscdotopen** [comment]
Thank you. I could reproduce the results. They seem to be related to missing values (nulls), as these rows will be missing in the groups formed during the computation. I need to investigate a bit how we can reenable the inclusion of the null values here without breaking other parts of the code.

**Comment by sscdotopen** [comment]
Thank you for bringing this issue to our attention. We have commited a fix to the current master branch.

**Comment by nuarc** [comment]
Thank you @sscdotopen
