### ISSUE TITLE
QUESTION: can configured _scalaCodeForConstraint be used as input to the VerificationSuite?

### ISSUE THREAD

**Issue by esil-esil** [awslabs/deequ#181]
Hi,

I am trying to use VerificationSuite with constraints manually defined in a config file, i.e. my constraints are not auto-generated from the ConstraintSuggestionRunner.

Though, for inspiration, I have investigated the output from ConstraintSuggestionsRunner (dataframe with the 3 columns: (1) column / (2) _constraintDescription / (3) _scalaCodeForConstraint ), and based on my manually defined config file, I have generated a sequence of strings with _scalaCodeForConstraint in the following format:

```
.isNonNegative("column_A")
.isComplete("column_B")
.isContainedIn("column_C", Array("validValue1", "validValue2"), _ >= 0.95, Some("It should be above 0.95!"))
```

I used your reply to https://github.com/awslabs/deequ/issues/140 as inspiration, and I would like to replace allConstraints (in your code example below with input from suggestionResult) with my sequence of _scalaCodeForConstraint.

```
   //-- How do I replace allConstraints below with _scalaCodeForConstraint based on config file??
   val allConstraints = suggestionResult.constraintSuggestions
      .flatMap { case (_, suggestions) => suggestions.map { _.constraint }}
      .toSeq  

    //-- probably also to be replaced ?? 
    val generatedCheck = Check(CheckLevel.Error, "generated constraints", allConstraints)

    val verificationResult = VerificationSuite()
      .onData(datasource)
      .addChecks(Seq(generatedCheck))
      .run()
```

Do you have a code example on how to use _scalaCodeForConstraint as input to the VerificationSuite?

Thank you very much in advance - your input is highly appreciated.

**Comment by sscdotopen** [comment]
Can you provide us more details about setup? Do you generate the Scala code as strings? This seems to be more complicated than necessary, you can just programmatically generate the check object itself.

**Comment by esil-esil** [comment]
Yes, I tried to specify the _scalaCodeForConstraint (many lines of .isNonNegative("column_A") ... .isComplete("column_B") etc., specific for various tables) in a config file (as indicated in first config snippet above). 
 For now, I will just go with hardcoding the _scalaCodeForConstraint directly in my code.
Thank you very much for your input.
