### ISSUE TITLE
Can't catch exception 

### ISSUE THREAD

**Issue by ngngocduc2205** [awslabs/deequ#182]
I can't catch exception  java.io.FileNotFoundException No such file or directory s3n://peter/data-669792474.bin. I try case notFound: FileNotFoundException. But it also can't.

val metricsAnalyzer = HdfsStateProvider(spark, "s3n://peter/data", 10, true)
    // define analyzers that compute metrics
    val analysis = Analysis().addAnalyzer(Size())
    try {
      AnalysisRunner.run(
            data = dataset,
            analysis = analysis,
            aggregateWith = Some(metricsAnalyzer))
    } catch {
      case _:Throwable => { AnalysisRunner.run(data = dataset, analysis = analysis, saveStatesWith = Some(metricsAnalyzer)) }
    }

**Comment by sscdotopen** [comment]
Can you give us a bit more context about your setup? How do you know that this exception is thrown? We try to avoid throwing out exceptions during the test execution. Every metric from the analysis result has a value attribute wrapped in a Try object. Maybe the exception that your are looking for is contained in this object.

**Comment by cport93** [comment]
I think it was the EMR version, because I was using 5.28.0 and it was giving me that error.
I have changed it to 5.27.0 and it works perfect for me.
