### ISSUE TITLE
Deequ is not a member of package com.amazon

### ISSUE THREAD

**Issue by cport93** [awslabs/deequ#183]
Hi, i'm trying to import some metrics from deequ but appears this error:
<console>:23: error: object deequ is not a member of package com.amazon

Trace:
`scala> import com.amazon.deequ.metrics.{DoubleMetric, Entity} 
<console>:23: error: object deequ is not a member of package com.amazon
       import com.amazon.deequ.metrics.{DoubleMetric, Entity}
`

Thank you so much for the help.

**Comment by sscdotopen** [comment]
Can you give us some more details with regard to your setup? Are you sure that you correctly included the deequ dependency in your classpath?
