### ISSUE TITLE
Growth of metrics repository file

### ISSUE THREAD

**Issue by awelsh93** [awslabs/deequ#187]
Hi,

We'd like to make use of the anomaly detection features of Deequ but this requires saving the computed metrics in a file. Each of our runs seems to add about 100KB to this json file. Running hourly jobs means the size of the metrics file becomes an issue after a while. Is it possible to trim this file or only keep the last x number of runs/days? We want to avoid a situation with a file that continues to grow in size.

Thanks.

**Comment by sscdotopen** [comment]
Hi,

We don't have a good answer on how to trim the file unfortunately.  We intentionally designed the repository to have a rather simple API https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/repository/MetricsRepository.scala.

I think in your case, it would make sense to implement a MetricsRepository backed by a database. Let us know if that is viable road for you and if you need some support in implement this.
