### ISSUE TITLE
Simple case examples for showing failed rows

### ISSUE THREAD

**Issue by kirillsc** [awslabs/deequ#188]
Hi, 

This is a follow up on the issue https://github.com/awslabs/deequ/issues/111

Currently I am following tutorial on running Deequ on EMR cluster (https://aws.amazon.com/blogs/big-data/test-data-quality-at-scale-with-deequ/). I would like to know how to use 
RowLevelSchemaValidator from spark in order to return a list of failed rows in the cases when it is possible. 

For example, if we verifying that values in a row are within certain range (positive, non null, less than, etc). 

A code snipped would be very useful. 

Thanks!
Kirill

**Comment by sscdotopen** [comment]
Hi Kirill,

I would point you to https://github.com/awslabs/deequ/blob/master/src/test/scala/com/amazon/deequ/schema/RowLevelSchemaValidatorTest.scala for some examples of the API usage

In general it works like this:

 **You define and validate a schema for the dataframe**

```scala
val schema = RowLevelSchema()
    .withIntColumn("id", isNullable = false)
    .withStringColumn("name", maxLength = Some(10))
    .withTimestampColumn("event_time", mask = "yyyy-MM-dd HH:mm:ss", isNullable = false)

val result = RowLevelSchemaValidator.validate(data, schema)
```
**After that you can access valid and invalid rows**

The valid rows are available via `result.validRows` and their count is available via `result.numValidRows`. The rows for which the constraints were not satisfied are available via `result.invalidRows` and their count is available via `result.numInvalidRows`.

**Comment by kirillsc** [comment]
Thank you for the example, it works great!

**Comment by neilsoncarlos** [comment]
would you guys have a quick guide on how to create a simple Python wrapper for this class or how to call it from a python script?

**Comment by iWantToKeepAnon** [comment]
> would you guys have a quick guide on how to create a simple Python wrapper for this class or how to call it from a python script?

Yes please!
