### ISSUE TITLE
Not able to merge 2 FrequenciesAndNumRows in Histogram analyzer

### ISSUE THREAD

**Issue by shashank-sharma** [awslabs/deequ#189]
I am trying to compute Histogram but originally I am interested in Frequency but behind the scene when I pass `saveStatesWith` parameter with `aggregateWith` to Histogram analyzer then it tries to merge its FrequenciesAndNumRows and fails to do it by giving error as:

`org.apache.spark.sql.AnalysisException: cannot resolve '`this.com_amazon_deequ_dq_metrics_count`' given input columns: [this.country, this.count, other.country, other.count]`

Is it possible that this feature is not yet fully implemented ?

**Comment by sscdotopen** [comment]
Hi Shashank, 

This sounds like a bug, as the merge should actually be working. Can you provide a code snippet for us so that we can reproduce the error?

Best,
Sebastian

**Comment by shashank-sharma** [comment]
@sscdotopen 

Error is with: https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala#L364

If I remove `COL_PREFIX` and keep `COUNT_COL = "count"` then it works perfectly fine
Do you think that's the solution ?

Initially I was trying to execute it by:

`Histogram("country").calculate(data, saveStatesWith = Option(stateStore))`
And then using it in:

`Histogram("country").calculate(data, saveStatesWith = Option(stateStore), aggregateWith= Option(secondStateStore))`

**Comment by sscdotopen** [comment]
Found the error and issued a PR for fixing it: https://github.com/awslabs/deequ/pull/190

Thank you for uncovering this!

**Comment by sscdotopen** [comment]
Shoudl work now!
