### ISSUE TITLE
VerificationSuite: verifying datatype string on a struct causes corrupt verification run

### ISSUE THREAD

**Issue by esil-esil** [awslabs/deequ#201]
Running constraint **.hasDataType("[fieldName]", ConstrainableDataTypes.String))** on a field of (erroneous) datatype struct, causes all other successful constraints to fail as well, i.e. affecting/corrupting all other valid constraint verifications that usually run succesfully. 

Failure symptom is identical to when (attempting) to run constraints on sub-levels of nested data. Running of most constraints (see exceptions below) on nested data also affects/corrupts all otherwise successful contraints in the same verification run.

I do know that constraints on nested data is not officially supported, but a few constraints actually do work on nested data, e.g. pattern matching constraints like e.g. .containsURL ... guessing (not tested) that other pattern matching constraints also do work on nested data. 

In such a corrupted run, the constraint_status is 'Failure' for all constraints (even though only 1 should fail), and the constraint_message (see example below) is almost identical to all constraints.

**Looks as if some error handling is needed, so that only the one erroneous constraint should fail, without affecting all other successful constraints in the same run.**

constraint_message example: 
org.apache.spark.sql.AnalysisException: cannot resolve 'StatefulDataType([fieldName1])' due to data type mismatch: argument 1 requires string type, however, '`[fieldName1]`' is of struct<[... LISTING THE ENTIRE STRUCT, which is loooooong]> type.;;
'Aggregate [sum(cast((verbType#15192 = completed) as bigint)) AS sum(CAST((verbType = completed) AS BIGINT))#15270L, sum(cast(cast(isnotnull(id#15180) as int) as bigint)) AS sum(CAST((id IS N... (chopped off in constraint_message)

**Comment by sscdotopen** [comment]
Thank you, this is a good catch. Deequ does not support nested data (e.g., struct fields). We should extend our preconditions in all Analyzer to check for this. Would you like to work on a PR for that?

**Comment by esil-esil** [comment]
@sscdotopen 
I would love to if I had the competencies, but I am software tester (not developer), so unfortunately, working on a PR is beyond my programming competencies :-/

Any other way we could ask the community for some help regarding a PR for this? E.g. prefixing the headline of this issue, or adding a specific Label to indicate request for help?

As always, thank you very much for your prompt response!

**Comment by sscdotopen** [comment]
We could address this PR together. Would you want to come up with a test case that shows how to produce this error? I can try to implement the fix then.

**Comment by esil-esil** [comment]
@sscdotopen 
Sure, sounds great!

I am thinking of creating a Databricks Notebook in which I create and populate a dataframe (without reading from files, but using .toDF), including running the constraint known to fail on the dataframe.

In that way I could export and upload the Notebook (or maybe just copy/paste the scala code?) for you to run - would that approach work for you?

**Comment by sscdotopen** [comment]
Yes, that sounds good!

**Comment by esil-esil** [comment]
@sscdotopen 
I will get back to you ... may take up to a week due to other priorities.

**Comment by esil-esil** [comment]
Hi @sscdotopen ,

I have now attached a source file export of a test case databricks notebook.

Explanation and comments are added in Cmd 1 of the notebook.

I have cleared 'State & Results' before export, but you should be able to run the entire notebook by going to (empty) Cmd 10 and click 'Run all above'.

Would it be possible for you to implement the errorHandling before next release of Deequ?

Thanks a lot for your help and contribution! Best regards, Lise

[TestCase_fatalError_constraintOnNestedData.zip](https://github.com/awslabs/deequ/files/4332621/TestCase_fatalError_constraintOnNestedData.zip)

**Comment by rambrus** [comment]
@esil-esil @sscdotopen 
Does it make sense to setup a whitelist for column types and add a precondition to all Analyzers that checks whether the column to be analyzed has a supported type.

At first glance, I would say these Spark column types supposed to be supported in Deequ:
```
	BooleanType

	DateType
	TimestampType
	CalendarIntervalType

	NullType

	ByteType
	DoubleType
	ShortType	
	IntegerType
	LongType
	FloatType

	StringType
```

What do you think about this approach? I think it's better to maintain a whitelist than a blacklist, since new types might turn up in upcoming Spark releases that should be:
- excluded by default
- reviewed by DEEQU team
- added to whitelist if they don't cause issues

**Comment by sscdotopen** [comment]
Most of the analyzers already have such checks, especially the ones that only apply to numerical columns. However there are some analyzers (like compliance) where we cannot automatically check the column type easily.

**Comment by esil-esil** [comment]
@rambrus : the errorHandling needed - see details and how-2-reproduce in attached Notebook above - is that the entire constraint verification run is corrupted, if just one of the constraints are testing for data type STRING on a column containing a STRUCT (and maybe other data types, not tested). Constraint testing for data type STRING on a column containing STRINGS works fine.

**Comment by lange-labs** [comment]
Closing after merging #214 #196
