### ISSUE TITLE
Example for using AnalysisRunner or ColumnProfiler with GroupMetric

### ISSUE THREAD

**Issue by voducvan** [awslabs/deequ#207]
Hi team and @sscdotopen  
We are researching about tools for data quality and find out that deeque is really promising, Our use case, is we have multiple large datasets and updated daily/intraday, Is there anyways to Use the AnalysisRunner and ColumnProfiler with group? eg, we wanna get the metric of uniqueness , or distinctness for each date or for each company.
 
For the VerificationRunner, It's possible to add check with Filter but dont know how to do it with AnlysisRunner/ColumnProfiler
if it's possible could you help with some snippet.

**Comment by voducvan** [comment]
hi @sscdotopen : Is this a proper channels to ask this question ?

**Comment by sscdotopen** [comment]
Hi voducvan,

For the columnprofiler, this is not possible, as it computes a fixed set of statistics. For the AnalysisRunner, you should be able to do it in the same way as for the VerificationSuite.

**Comment by voducvan** [comment]
but It will be time-consuming, since it will be classified into different group aka different submitted jobs, while we have some functions like "CountDistinct" to support this scenario "to groupby a field "_c1" and count the distinct number of values from field "_c2"

**Comment by sscdotopen** [comment]
You are absolutely right, and we have had a lot of requests for this feature already, but did not have the time to integrate it unfortunately.

The problem is that this computation might be very difficult to scale if there is a larger number of groups in the data.

**Comment by voducvan** [comment]
ah thanks for your clarification, if we find a way to deal with this, will submit a PR back !
