### ISSUE TITLE
Release 1.0.3-RC2 - Maven

### ISSUE THREAD

**Issue by jameswinegar** [awslabs/deequ#219]
This issue might be a little premature (5 hours since release tag) but the release cut hasn't been pushed to Maven yet.

**Comment by tdhd** [comment]
Please allow for some more time to let the release be visible on maven central. If the issue persists please feel free to reopen this ticket.

**Comment by tdhd** [comment]
The release is now available: https://search.maven.org/artifact/com.amazon.deequ/deequ/1.0.3-rc2/jar

**Comment by sscdotopen** [comment]
Thank you for pushing this out!

**Comment by jameswinegar** [comment]
Thank you @tdhd!
