### ISSUE TITLE
Add check constriant to take list as parameters

### ISSUE THREAD

**Issue by Karan970** [awslabs/deequ#225]
The addcheck functions , don't take list of columns has a parameter for most of it's constraint check , because of this we can't a generic code, this is posing us problem because of the scale of the table we have , example

I need check the completness,uniqueness , primaryKey constraint  for all the columns in pk_list string array
  val verificationResult_df: VerificationResult = { VerificationSuite()
                  .onData(res_dq_after_schema)
                  .addCheck(
                    Check(CheckLevel.Error, "Data Quality Check")
                      .hasSize(_ >= 500000)
                      .isUnique(pk_list) // should not contain duplicates
                      .isComplete(pk_list) // should never be NULL// should never be NULL
                      .isPrimaryKey(pk_list)
                  )
                      .run()
                }

Couldn't relevant functions where we can achieve this ? 
Probably do we need to have constraints that takes list has input parameter ?

**Comment by jameswinegar** [comment]
Take advantage of the fact that deequ exposes everything as method chaining of constraints. Maybe something like this works

```{scala}
val pk_list = Seq("col1","col2")

val _check = Check(CheckLevel.Error, "Data Validation Check")

pk_list.foreach { column => 
  _check
  .isUnique(column)
  .isComplete(column)
  .isPrimaryKey(column)
}
```

**Comment by Karan970** [comment]
Hey James,

I agree to that! But what about the PrimaryKey constraint for  composite keys , above code would individual check each of the columns for Primarily constraint !
