### ISSUE TITLE
Release-1.0.3 - Maven

### ISSUE THREAD

**Issue by pengzai6666** [awslabs/deequ#226]
I am not sure if this issue has been raised before, I would apologize if it has been asked but I didn't find the exact issue in history: are we planning to release an official v1.0.3 recently? Or do we have a schedule for releasing it? I could only find rc versions in Maven. Thanks!

**Comment by abnagara** [comment]
Could you please help with this, @sscdotopen ?

**Comment by lange-labs** [comment]
Release was completed, closing
