### ISSUE TITLE
AnalysisRunner passing same exact Analyzer should count as one single Analyzer

### ISSUE THREAD

**Issue by shashank-sharma** [awslabs/deequ#227]
Ideally the case should be, if I specify one Analyzer multiple times, then it should consider it as 1 single analyzer, right now output is as intended it gives 1 metric but there is still computation happening behind the scenes

To replicate I have written minimal code as an example which add same analyzer multiple time just to check how much time it took to run (also in code I verified that it is running it)

```
import com.amazon.deequ.analyzers.runners.AnalysisRunner
import com.amazon.deequ.analyzers.Size

case class Item(
  id: Long,
  productName: String,
  description: String,
  priority: String,
  numViews: Long
)

val rdd = spark.sparkContext.parallelize(Seq(
  Item(1, "Thingy A", "awesome thing.", "high", 0),
  Item(2, "Thingy B", "available at http://thingb.com", null, 0),
  Item(3, null, null, "low", 5),
  Item(4, "Thingy D", "checkout https://thingd.ca", "low", 10),
  Item(5, "Thingy E", null, "high", 12)))

val data = spark.createDataFrame(rdd)

def test(count: Int): Unit = {
  val startNanoTime = System.nanoTime()
  val result = AnalysisRunner.onData(data).addAnalyzers(List.fill(count)(Size())).run()
  println(s"${(System.nanoTime() - startNanoTime) / 1000000000.0}")
}

test(1)
test(100)
test(1000)
test(10000)
```

Right now with 1.0.3-RC1 output is:

```
0.094738479
0.658176572
2.00287351
16.243372952
```

After reading code if we make one small change in:

https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/runners/AnalysisRunner.scala#L113
to
`val allAnalyzers = analyzers.map { _.asInstanceOf[Analyzer[State[_], Metric[_]]] }.distinct`
Then output is
```
0.119323052
0.102618298
0.104985755
0.107584708
```

This can be useful when working with bigger dataset and making use of VerificationSuite as:

```
  val verificationResult = VerificationSuite()
    .onData(data)
    .addRequiredAnalyzer(Size())
    .addCheck(Check(CheckLevel.Error, "size check").hasSize(_ == 5))
    .run() 
```

Here it should compute for size once but in this run at:

https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/VerificationSuite.scala#L119

It will send analyzers Seq of 2 Size analyzers and it will compute twice which is not ideal

**Comment by shashank-sharma** [comment]
If possible I would like to make PR to solve this

**Comment by sscdotopen** [comment]
Dear Shashank, 
I am afraid this is not a reliable way to benchmark Spark applications. There is a huge startup cost involved in Spark and its also notoriously difficult to correctly conduct microbenchmark for JVM code which is subject to hotspot JIT compilation.

Can you record the number of Spark jobs issued? That would be a reliable metric. 

Alternatively, we could also throw an error if a given analyzer is specified multiple times.

Best,
Sebastian

**Comment by shashank-sharma** [comment]
@sscdotopen I understand and that does make sense, I mentioned time as a metric just to prove a point but at the end multiple analyzers were getting executed (after using debug tools) and execution is in code block:

https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/runners/AnalysisRunner.scala#L313

Regarding above comment, here is what I have:

I ran above snippet in sparkshell and executed 3 times separately in order of:

test(1000)
test(10000)
test(50000)
 
For each snippet, it issued 1 spark job with total of 9 tasks

![Screenshot from 2020-04-17 22-14-04](https://user-images.githubusercontent.com/9320644/79593323-ea567200-80f8-11ea-9501-22ede9a1a7e2.png)

As for solution can't we simply allow the execution with only distinct analyzers ?

**Comment by sscdotopen** [comment]
There is only one Spark job generated, which is fine. We will generate a SparkSQL query with repeated aggregation functions which the SQL execution engine should handle and only compute the aggregation once. So there is no performance problem here.

Nevertheless, I think we should simply throw an exception if a user wants to run an Analysis with multiple copies of the same Analyzer. Would you like to submit a PR for that?

**Comment by shashank-sharma** [comment]
Got it, yes I would love to do that, will do that as soon as possible, Thanks

**Comment by shashank-sharma** [comment]
Fixed
