### ISSUE TITLE
Adding custom constraints

### ISSUE THREAD

**Issue by timgent** [awslabs/deequ#230]
How would it be recommended for us to add some custom constraint in our codebase? For example we would like to check our data conforms to some more complex properties that we would need to define our own constraint for.

Most of the existing constraints are AnalysisBasedConstraint, which is private to deequ, so it's not possible to create a new constraint of that type. However the base Constraint type is possible to extend.

Any recommendations on how to implement our own constraints?

**Comment by sscdotopen** [comment]
Hi,

First, I would suggest to see if you can just use https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/Compliance.scala to express your constraint. If that doesn't work, it would be great if you could share a few more details on what you want to look for.

Deequ only supports constraints on statistics that can be efficiently computed on large datasets, so there might be cases would be hard to fit in.

**Comment by timgent** [comment]
Thanks for the quick response @sscdotopen .

I don't think Compliance would suffice, as some conditions we'd like to check are across multiple rows of data, though arguably we could potentially re-shape our data to be able to do validations on a single line.

A more concrete example of the type of thing we want to do.

Imagine we have a Dataset with data like:
```
case class UserEvent(user_id: String, event_type: String, start_date: Date, end_date: Date)
```

We have a job which (among other things...) should combine any user events where the event type is the same, and they either overlap, or are less than 20 days apart. The output dataset has the same fields.

So one QC check we would like to do is check that there are no events for a user with the same event_type and fewer than 20 days between them.

While this scenario is quite simple, we have other similar checks with more complexity in the transformation code, and have found real data can give us edge cases we've not considered in our unit tests, so checking some properties like this can be pretty helpful.

Any thoughts appreciated

**Comment by sscdotopen** [comment]
Hmm, I don't think such a constraint is a good fit for Deequ, we mostly focus on data quality metrics that can be efficiently run as aggregation queries.

Your use case sounds like it requires a self join on user which can become very costly. It would recommend to run this outside of Deequ.

**Comment by timgent** [comment]
Rather than a self-join, it can also be achieved by:
* Grouping on user id and event_type, and collecting an ordered list of start_date, end_date
* Using a UDF which takes this ordered list and checks the size of gaps between the entries
* If any entry has a gap less than 20 days, the check is failed

Still not as efficient as the other types of queries deequ currently supports I think, though we find performance fairly reasonable. However as you say supporting such arbitrary checks doesn't sound like what deequ is aiming for at the moment?

**Comment by sscdotopen** [comment]
"Grouping on user id and event_type, and collecting an ordered list of start_date, end_date" <- that is exactly what a self join does :)

**Comment by sscdotopen** [comment]
Yes, your check would not be a good fit for Deequ at the moment.

**Comment by timgent** [comment]
Thanks for the feedback and discussion :) I'll close the issue
