### ISSUE TITLE
 "code_for_constraint": ".isContainedIn(...) not seen for columns with many values in ConstraintSuggestions

### ISSUE THREAD

**Issue by ravimadhu3** [awslabs/deequ#231]
Hi ,

When we run --

ConstraintSuggestionRunner ()
    .onData (df)
      .addConstraintRules (Rules.DEFAULT)
      .run ()

For some columns - say REASONDESCRIPTION we get - 

 "code_for_constraint": ".isContainedIn(\"REASONDESCRIPTION\", Array(\"Normal pregnancy\", \"Atrial Fibrillation\",.....

For another column - "DESCRIPTION" that has values all the way through 

We do not get this line at all  -> "code_for_constraint": ".isContainedIn(...)

Please guide me on what I might be missing to get lists of values for every column.

Thanks

**Comment by sscdotopen** [comment]
We only compute this list for columns with less than approximately 120 distinct values, because we want to avoid having to shuffle the data.

https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala#L71

Do you have an idea how many distinct values your columns of interest might have? We could think about making the threshold configurable.

**Comment by ravimadhu3** [comment]
Thanks for getting back - we tested it with 119 distinct values in the DESCRIPTION column and its worked as mentioned by you.

Anything more - did not show up at all for some columns.

Our files will have more than 120 distinct values - it could run in the 10's of thousands - as we work on healthcare data - a configurable threshold will be useful.

 In the meantime we will try rebuilding the code with a different threshold - in
 
https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/profiles/ColumnProfiler.scala#L71

Thanks again.

**Comment by sscdotopen** [comment]
Would you like to create a PR to make the threshold configurable?

**Comment by ravimadhu3** [comment]
Sure will do. I am going to close this issue for now. Thanks
