### ISSUE TITLE
Analyzer should support spark.sql.caseSensitive property

### ISSUE THREAD

**Issue by jaesjun** [awslabs/deequ#236]
Spark has property for case sensitivity, spark.sql.caseSensitive. It it set false, then analyzer should be working in case insensitive manner.

So the below two test should pass.

1. small leter column.  
  "return results for configured analyzers" in withSparkSession { sparkSession =>

      val df = getDfFull(sparkSession)

      val analysisResult = Analysis()
        .addAnalyzer(Size())
        .addAnalyzer(Distinctness("item"))
        .addAnalyzer(Completeness("att1"))
        .addAnalyzer(Uniqueness(Seq("att1", "att2")))
        .run(df)

      val successMetricsAsDataFrame = AnalyzerContext
        .successMetricsAsDataFrame(sparkSession, analysisResult)

      import sparkSession.implicits._
      val expected = Seq(
        ("Dataset", "*", "Size", 4.0),
        ("Column", "item", "Distinctness", 1.0),
        ("Column", "att1", "Completeness", 1.0),
        ("Mutlicolumn", "att1,att2", "Uniqueness", 0.25))
        .toDF("entity", "instance", "name", "value")

      assertSameRows(successMetricsAsDataFrame, expected)
    }

2. capital letter column.

    "return results for configured analyzers in case insensitive manner" in withSparkSession { sparkSession =>

      sparkSession.sqlContext.setConf("spark.sql.caseSensitive", "false")

      val df = getDfFull(sparkSession)

      val analysisResult = Analysis()
        .addAnalyzer(Size())
        .addAnalyzer(Distinctness("ITEM"))
        .addAnalyzer(Completeness("ATT1"))
        .addAnalyzer(Uniqueness(Seq("ATT1", "ATT2")))
        .run(df)

      val successMetricsAsDataFrame = AnalyzerContext
        .successMetricsAsDataFrame(sparkSession, analysisResult)

      import sparkSession.implicits._
      val expected = Seq(
        ("Dataset", "*", "Size", 4.0),
        ("Column", "ITEM", "Distinctness", 1.0),
        ("Column", "ATT1", "Completeness", 1.0),
        ("Mutlicolumn", "ATT1,ATT2", "Uniqueness", 0.25))
        .toDF("entity", "instance", "name", "value")
      assertSameRows(successMetricsAsDataFrame, expected)
    }

**Comment by sscdotopen** [comment]
Thank you for raising this issue. Would you be willing to work on a PR to fix this?

**Comment by jaesjun** [comment]
Yes, I'll make PR. 
thanks.

**Comment by jaesjun** [comment]
@sscdotopen Hi, I've implemented this but I don't have permission to push my local branch.

**Comment by jaesjun** [comment]
> Thank you for raising this issue. Would you be willing to work on a PR to fix this?
Hi, I've implemented this but I don't have permission to push my local branch.

**Comment by sscdotopen** [comment]
You can fork deequ and push your branch to your forked repository to create a PR.

**Comment by jaesjun** [comment]
i've made a PR, https://github.com/awslabs/deequ/pull/241

**Comment by jaesjun** [comment]
PR, https://github.com/awslabs/deequ/pull/241, was merged
