### ISSUE TITLE
Support "Collect Only" Checks in VerificationSuite

### ISSUE THREAD

**Issue by rambrus** [awslabs/deequ#237]
We have a use case where we process several metrics on a dataset, some of them need to be checked, some of them need to be only collected (we don't have any requirement for these cases, just want to see the historical trends, maybe we can come up with an expected value after a while)

e.g.
```
    AnalysisRunner
      .onData(data)
      .addAnalyzers(Completeness("col1"))
      .addAnalyzer(Completeness("col2"))

      .useRepository(repository)
      .saveOrAppendResult(resultKey)
      .run()
```

```
    VerificationSuite
      .onData(data)
      .addCheck(
        Check(CheckLevel.Error, "unit testing my data")
          .hasSize(_ > 100)
          .isComplete("col3")
          .isUnique("col3")
        )) 
      .useRepository(repository)
      .saveOrAppendResult(resultKey)
      .run()
```

This solution looks a bit verbose to me and results code duplication. I was wondering if we could add a *collect only* feature to *VerificationSuite* to reduce duplication?

I mean something like this:
```
    VerificationSuite
      .onData(data)
      .addCheck(
        Check(CheckLevel.Error, "unit testing my data")
          .hasSize(_ > 100)
          .hasCompleteness("col1", Check.CollectOnly)
          .hasCompleteness("col2", Check.CollectOnly)
          .isComplete("col3")
          .isUnique("col3")
        )) 
      .useRepository(repository)
      .saveOrAppendResult(resultKey)
      .run()
```

```
  val CollectOnly: Double => Boolean = { _ => true }
```

What do you think? Would this approach work or would it result confusions?

**Comment by sscdotopen** [comment]
Hi,

This is already possible by using the method `addRequiredAnalyzer` on the VerificationSuite:

https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/VerificationRunBuilder.scala#L122

**Comment by rambrus** [comment]
Perfect, thanks for the hint!
