### ISSUE TITLE
Spelling mistake: MutliColumn -> MultiColumn

### ISSUE THREAD

**Issue by zuston** [awslabs/deequ#239]

**Comment by zuston** [comment]
[PR is here.](https://github.com/awslabs/deequ/pull/238)

**Comment by sscdotopen** [comment]
Dear Zuston,

This is a very old bug and unfortunately, fixing it in the current version would break serialized metrics, so we decided a long time ago to keep this spelling mistake....

**Comment by zuston** [comment]
Thank your reply. Ok, I close this issue ~
