### ISSUE TITLE
Constraint status message

### ISSUE THREAD

**Issue by albertusk95** [awslabs/deequ#245]
I tried running the example on the README. The dummy data used was the following.

```scala
val rdd = spark.sparkContext.parallelize(Seq(
  Item(1, "Thingy A", "awesome thing.", "high", 0),
  Item(2, "Thingy B", "available at http://thingb.com", null, 0),
  Item(3, null, null, "low", 5),
  Item(4, "Thingy D", "checkout https://thingd.ca", "low", 10),
  Item(5, "Thingy E", null, "high", 12)))

val data = spark.createDataFrame(rdd)
```

After running the `VerificationSuite`, I checked the constraint status with the following code (same as the one on README).

```scala
import com.amazon.deequ.constraints.ConstraintStatus


if (verificationResult.status == CheckStatus.Success) {
  println("The data passed the test, everything is fine!")
} else {
  println("We found errors in the data:\n")

  val resultsForAllConstraints = verificationResult.checkResults
    .flatMap { case (_, checkResult) => checkResult.constraintResults }

  resultsForAllConstraints
    .filter { _.status != ConstraintStatus.Success }
    .foreach { result => println(s"${result.constraint}: ${result.message.get}") }
}
```

The followings were the returned result.

```
We found errors in the data:

CompletenessConstraint(Completeness(productName)): Value: 0.8 does not meet the requirement!
PatternConstraint(containsURL(description)): Value: 0.4 does not meet the requirement!
```

The concern is that **shouldn't the message be like the followings?**

```
CompletenessConstraint(Completeness(productName)): Value: 0.2 does not meet the requirement!
PatternConstraint(containsURL(description)): Value: 0.6 does not meet the requirement!
```

Thanks.

**Comment by TammoR** [comment]
Hi, I"m not sure I understand the concern. Assuming that "product name" is your second column ("Thingy A", ...) this has 1 out of 5 null values and is therefore 4/5 = 0.8 complete.
The same applies to the "description" column. Does this make sense?

**Comment by albertusk95** [comment]
@TammoR Thanks. Yes, that makes sense. However, what is the meaning of the message "Value: 0.8 **does not meet** the requirement!"?

Since the "requirement" for the "productName" column is **never be NULL**, shouldn't the message be "Value: 0.8 **meets** the requirement"?

**Comment by chenliu0831** [comment]
Yeah actually the ratio value in error message logic in Deequ has been incorrect:

1. Ratio metrics comes from the [NumMatchesAndCount](https://github.com/awslabs/deequ/blob/d3dbe2d77563fdbe0acaadcf55bd84e5f688027f/src/main/scala/com/amazon/deequ/analyzers/Analyzer.scala#L242) method which report `ratio` that matches
2. Constraint message is templated to report ratio that does not match. So it really should be `1 - ratio` above. https://github.com/awslabs/deequ/blob/d3dbe2d77563fdbe0acaadcf55bd84e5f688027f/src/main/scala/com/amazon/deequ/constraints/AnalysisBasedConstraint.scala#L79
