### ISSUE TITLE
Histogram metrics backward compatibility issue in 1.0.3-rc2 build

### ISSUE THREAD

**Issue by rambrus** [awslabs/deequ#246]
Build `1.0.3-rc2` is breaking the backward compatibility of `Histogram` analyzer.
Created a small snippet to demo the issue:
```
    import spark.implicits._

    val inputDF = Seq((1, "a"), (2, "b")).toDF("index", "value")

    val analysisResult = AnalysisRunner
      .onData(inputDF)

      .addAnalyzer(Histogram("value"))
      .run()

    AnalyzerContext.successMetricsAsDataFrame(spark, analysisResult).show()
```

The above snippet is producing this output on both `1.0.2` and `1.0.3-RC1` builds:
```
+------+--------+-----------------+-----+
|entity|instance|             name|value|
+------+--------+-----------------+-----+
|Column|   value|   Histogram.bins|  2.0|
|Column|   value|  Histogram.abs.a|  1.0|
|Column|   value|Histogram.ratio.a|  0.5|
|Column|   value|  Histogram.abs.b|  1.0|
|Column|   value|Histogram.ratio.b|  0.5|
+------+--------+-----------------+-----+
```

In `1.0.3-rc2` we have this output:
```
+------+--------+---------+-----+
|entity|instance|     name|value|
+------+--------+---------+-----+
|Column|   value|Histogram|  2.0|
|Column|   value|Histogram|  1.0|
|Column|   value|Histogram|  0.5|
|Column|   value|Histogram|  1.0|
|Column|   value|Histogram|  0.5|
+------+--------+---------+-----+
```

So, one of these changes affected this part in https://github.com/awslabs/deequ/compare/1.0.3-rc1...1.0.3-rc2

I did some refactoring around this area in these PRs:
https://github.com/awslabs/deequ/pull/194
https://github.com/awslabs/deequ/pull/206

Any ideas / hints are welcome.

**Comment by rambrus** [comment]
This might cause the issue: https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/analyzers/runners/AnalyzerContext.scala#L109

**Comment by rambrus** [comment]
I think we need to use `metric.name` instead of `analyzer.getClass.getSimpleName`. Will take a look a raise a PR for the fix.

**Comment by zuston** [comment]
I meet the same problem. This PR looks good to me.

**Comment by tdhd** [comment]
Closing this, PR #247 is merged.

**Comment by skunapareddy-godaddy** [comment]
hi @rambrus What's exactly the abs, ratio, and bins?
