### ISSUE TITLE
Problem using deequ with EMR and Spark 2.4.5

### ISSUE THREAD

**Issue by fenimore** [awslabs/deequ#251]
Hi! I found a closed issue 

> We are testing our release on EMR clusters with Spark 2.3 and 2.4, so deequ should work without problems with these Spark versions. If you run into an issue, don't hesitate to open a ticket here.

_Originally posted by @sscdotopen in https://github.com/awslabs/deequ/issues/139#issuecomment-532199231_

I am having issues with doing just this actually. This is happening after spinning up an EMR cluster and its Jupyter notebook. When I try to include deeque using the `configure` escaped command in the first cell, 
```
%%configure -f
{
    "conf": {"spark.jars.packages": "com.amazon.deequ:deequ:1.0.2"}
}
```

I run into a dependency issue, and that's how I found this closed issue on the Spark board: https://issues.apache.org/jira/browse/SPARK-24074?focusedCommentId=17103793&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17103793
from the issue:

> From some reason spark downloads a javadoc artifact of a package instead of the jar.

Should I install Deequ differently?

The (truncated) stacktrace that prints when I try to init the Spark Session is:
```
20/06/01 18:57:14 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/com.github.fommil.netlib_core-1.1.2.jar -> hdfs://ip-172-31-29-127.eu-west-1.compute.internal:8020/user/livy/.sparkStaging/application_1591014320254_0006/com.github.fommil.netlib_core-1.1.2.jar
20/06/01 18:57:14 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/net.sourceforge.f2j_arpack_combined_all-0.1.jar -> hdfs://ip-172-31-29-127.eu-west-1.compute.internal:8020/user/livy/.sparkStaging/application_1591014320254_0006/net.sourceforge.f2j_arpack_combined_all-0.1.jar
20/06/01 18:57:14 INFO Client: Deleted staging directory hdfs://ip-172-31-29-127.eu-west-1.compute.internal:8020/user/livy/.sparkStaging/application_1591014320254_0006
20/06/01 18:57:14 ERROR SparkContext: Error initializing SparkContext.
java.io.FileNotFoundException: File file:/var/lib/livy/.ivy2/jars/net.sourceforge.f2j_arpack_combined_all-0.1.jar does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:640)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:866)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:630)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:452)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:340)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:292).
```

**Comment by gucciwang** [comment]
I ran into a similar issue when building deequ -- I bypassed the problem by just removing the `net.sourceforge.f2j_arpack_combined_all-0.1.jar` dependency. It's a Fortran 2 Java package that I haven't necessarily seen used in my work so far with deequ. Here's how I created my pySpark session to exclude the dependency then everything ran smoothly! 

```
deequ_maven_coord = "com.amazon.deequ:deequ:1.0.3-rc2"
f2j_maven_coord = "net.sourceforge.f2j:arpack_combined_all" 

spark = (SparkSession
    .builder
    .config("spark.jars.packages", deequ_maven_coord)
    .config("spark.jars.excludes", f2j_maven_coord)
    .getOrCreate())
```

**Comment by fenimore** [comment]
Thanks @gucciwang this did work! 

I also didn't realize I could use deequ with PySpark, so thanks twice!
