### ISSUE TITLE
Wrong release version in tag 1.0.3

### ISSUE THREAD

**Issue by zuston** [awslabs/deequ#255]
The repo tag 1.0.3 's version should be 1.0.3 in pom.xml.
But now it's still 1.1.0-SNAPSHOT

**Comment by tdhd** [comment]
This was made by mistake, we are releasing 1.0.4 soon to address the wrong version in pom.xml.

**Comment by tdhd** [comment]
Thank you for reporting this. 1.0.4 is now with the correct version in pom.xml and should be on Maven soon.
