### ISSUE TITLE
.NET porting

### ISSUE THREAD

**Issue by samueleresca** [awslabs/deequ#266]
Hi, 
I'm porting the full deequ library in .NET; you can see WIP porting here:  [samueleresca/deequ.net](https://github.com/samueleresca/deequ.net). Can you see any restriction or limitation that doesn't allow me to do that?

**Comment by sscdotopen** [comment]
Hi Samuel, 

I am super excited to see this happening! I am not a lawyer, but my layman understanding is that the Apache License allows you to fork, modify and redistribute our code as long as you give us contribution for the original code.

**Comment by lange-labs** [comment]
Thanks for sharing this work.

Resolving due to inactivity.
