### ISSUE TITLE
Is it possible to implement a multi-column constraint?

### ISSUE THREAD

**Issue by mikeperetz** [awslabs/deequ#272]
Hi! Is it possible to have a check span multiple columns. For example:

`if colA > 5 and colB != NULL then Pass`

**Comment by sscdotopen** [comment]
Yes, you can pass a SparkSQL expression to `satisfies` https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/checks/Check.scala#L667
