### ISSUE TITLE
Duplicate suggestion for one column

### ISSUE THREAD

**Issue by dmiljkovic** [awslabs/deequ#273]
Below code produces duplicated suggestions i.e. for column "state" two isContainedIn are produced

isComplete("state")
isContainedIn("state", Array("NY", "CA", "RI", "SC", "NC", "NH", "WI", "FL", "NE", "MD", "SD", "AK", "MA"))
isContainedIn("state", Array("NY", "CA", "RI", "SC", "NC", "NH", "WI", "FL", "NE", "MD", "SD", "AK"), _ >= 0.84, Some("It should be above 0.84!"))

import com.amazon.deequ.SparkContextSpec
import com.amazon.deequ.suggestions.{ConstraintSuggestionRunner, Rules}
import com.amazon.deequ.utils.FixtureSupport
import org.apache.spark.sql.{DataFrame, SparkSession}
import org.scalatest.{Matchers, WordSpec}

class TestSuggestions extends WordSpec with Matchers with SparkContextSpec with FixtureSupport {

  def testData(sparkSession: SparkSession): DataFrame = {
    import sparkSession.implicits._

    Seq(
      ("CA"),
      ("SD"),
      ("NC"),
      ("SD"),
      ("WI"),
      ("MD"),
      ("NE"),
      ("MD"),
      ("MA"),
      ("FL"),
      ("WI"),
      ("MA"),
      ("CA"),
      ("SC"),
      ("AK"),
      ("NY"),
      ("NH"),
      ("NE"),
      ("SC"),
      ("AK"),
      ("CA"),
      ("NY"),
      ("NC"),
      ("RI"),
      ("NY"),
      ("CA"),
      ("NH"),
      ("NY"),
      ("RI"),
      ("FL")
    )
      .toDF("state")
  }

  "duplicateSuggestion" should {

    "" in withSparkSession { session =>

      val data = testData(session)
      data.show(false)
      val suggestionResult = ConstraintSuggestionRunner()
        .onData(data)
        .addConstraintRules(Rules.DEFAULT)
        .run()
      suggestionResult.constraintSuggestions.foreach { case (column, suggestions) =>
        suggestions.foreach { suggestion =>
          println(s"Constraint suggestion for '$column':\t${suggestion.description}\n" +
            s"The corresponding scala code is ${suggestion.codeForConstraint}\n")
        }
      }
    }
  }
}

**Comment by sscdotopen** [comment]
The `isContainedIn` suggestions are not duplicates of each other. The first one states that ALL the values of the column are contained in the array, while the second one states that only 84% of the values are contained in the column. It is up to you to decide which of the suggested constraints applies to your data.

**Comment by dmiljkovic** [comment]
Thanks for the quick answer. Is this scenario, giving multiple options,  specific only to isConstrainedIn  or ConstraintSuggestion procedure can give multiple options for any constraint.

**Comment by sscdotopen** [comment]
You can specify a set of rules that generate constraints as shown here https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/examples/constraint_suggestion_example.md These rules determine which constraints will be suggested.
