### ISSUE TITLE
VerificationSuite when converted to DataFrame we don't have constraint column

### ISSUE THREAD

**Issue by TimmannaC** [awslabs/deequ#277]
Hi,

We are planning for an use case where we want to stored the metrics computed from VerificationSuite into the database.

Our next application will read from database and perform some necessary action on the failed columns.

As per my understanding deequ doesn't support database as repository option. To achieve our use-case we are planning to convert the VerificationSuite metrics into dataframe and then write it to database.

When i convert to dataframe i able to see the constraint_status and constraint_message.

**requirement.**
Can we hv one more column in dataframe with constraint column name.

**Example**

Currently we getting below ouput from dataframe.

check_status | constraint | constraint_status | constraint_message
-- | -- | -- | --

Expectation from us.

check_status | constraint | constraint_status | constraint_message | constraint_column
-- | -- | -- | -- | --

appreciate your response.

Thanks

**Comment by sscdotopen** [comment]
Unfortunately, there is not always a column name available for a constraint, as constraints can apply to multiple columns or can originate from custom SQL expressions.

**Comment by TimmannaC** [comment]
Hi Sebastian,
Thanks for your response.
