### ISSUE TITLE
Possibility of performing histogram analysis on predefined ranges

### ISSUE THREAD

**Issue by eapframework** [awslabs/deequ#280]
Hi All, I wanted to perform Histogram analysis on predefined range values. For example

Column   Name | Value_range | Percentage
-- | -- | --
A37B | 0 | 2.724410%
A37B | 1-1,000 | 3.661120%
A37B | 1,001-2,500 | 2.122090%
A37B | 2,501-5,000 | 1.992950%
A37B | 5,001-10,000 | 2.038750%
A37B | 9999999 | 83.961500%
A37B | 10,001-25,000 | 1.798010%
A37B | 25,001-50,000 | 0.497160%
A37B | 50,001-100,000 | 0.277460%
A37B | 100,000-9,999,998 | 0.620890%
A37B | Missing | 0.305660%

I wanted to calculate the percentage of records in each range (0, 1-1000, 1001-2500, 5001,10000,etc)

Please let me how to perform this analysis using deequ library. Thanks!

**Comment by sscdotopen** [comment]
You can specify a bucketing function for the histogram
