### ISSUE TITLE
How to get Spark expression of a failed check?

### ISSUE THREAD

**Issue by yauhen-sobaleu** [awslabs/deequ#285]
Is there a way to dynamically get a Spark expression that was used for a certain Check? It will allow to filter the dataframe and quickly find rows with bad quality.

**Comment by sscdotopen** [comment]
Unfortunately, this a bit more difficult. Deequ generates queries that combine the statistics generation for multiple checks, and it is often not possible to pinpoint the "bad" rows. However, we offer the https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/schema/RowLevelSchemaValidator.scala for this usecase.

**Comment by yauhen-sobaleu** [comment]
Thank you

**Comment by gauravbrills** [comment]
@yauhen-sobaleu we use the constraint result and parse the expression via regex to filter out on most rules . You could use this but yes this works mostly for satisfies ,size ,completeness and simpler checks for statistics like entropy,stddev,correlation or others it might be bit complicated.
