### ISSUE TITLE
Getting lowerbound and upperbound values dynamically for `isContainedIn` constraint  using spark sql

### ISSUE THREAD

**Issue by eapframework** [awslabs/deequ#289]
Everyday Mean values are getting updated in the historical table `df`.

       Date     	Mean_val
       09/01	2
       09/02	3.5
       09/03	4.5
       09/04	3
       09/05	3.5
       09/06        3.7 
       09/07	4

I need to check whether current mean value is between historical min mean and max mean value. For example, Check whether `4` is between `2` and `4.5`.  
How to perform this check using `isContainedIn` constraint with lowerbound and upperbound values.

Is it possible to get lowerbound and upperbound dynamically from Spark SQL and use it in constraint
select min(Mean_val) from df where Date <  current_Date
select max(Mean_val) from df where Date <  current_Date

**Comment by sscdotopen** [comment]
This sounds like a use case for our anomaly detection functionality, here is some more details for that: https://github.com/awslabs/deequ/blob/master/src/main/scala/com/amazon/deequ/examples/anomaly_detection_example.md
