### ISSUE TITLE
Holt Winters - series periodicity

### ISSUE THREAD

**Issue by edenGlu** [awslabs/deequ#296]
Is there a way to use deequ , holt winters algorithm on data with :
series seasonality - hourly, and metric interval - daily?

**Comment by sscdotopen** [comment]
Deequ only allows you to run anomaly detection algorithms on the metrics computed from the data, not on the data itself.

**Comment by edenGlu** [comment]
the question is about the series periodicity options, whether the seasonality might be hourly.
Because i can't notice it in the code or documents.

**Comment by zeotuan** [comment]
This would be a nice addition to deequ to support hourly interval and daily seasonality. I will add a PR

**Comment by zeotuan** [comment]
@rdsharma26 can we close this issue? closed with #546

**Comment by rdsharma26** [comment]
Thanks @zeotuan
