### ISSUE TITLE
Column Profiler reads String column with all values empty improperly

### ISSUE THREAD

**Issue by academy-codex** [awslabs/deequ#301]
1. In case all values of a String column are empty ("") then the profiler suggests an Integer data type.
2. In case all values are empty("") then profiler still suggests completeness of 1.0. This might not always be the case for a user. The user may want to check if data is present or not, meaning "" should mean incomplete for the user. We should have flexibility to provide the inference of empty strings ("") as data present or not present from the columnprofiler() point of view.

**Comment by academy-codex** [comment]
We should have the second option as a parameter in the ColumnProfilerRunBuilder()

**Comment by academy-codex** [comment]
@sscdotopen

**Comment by sscdotopen** [comment]
Hi, the first case sounds like a bug, could you provide a test/PR for that? That would be awesome.

The second case is fine, as completeness by definition looks at NULL values. If you want to interpret empty string as missing (which is a custom semantic), I suggest you preprocess the data accordingly.

**Comment by academy-codex** [comment]
@sscdotopen Have raised a PR for this with a test case.
