### ISSUE TITLE
Filter for CountDistinct Analyzer

### ISSUE THREAD

**Issue by mschandra18** [awslabs/deequ#304]
All of the analyzers have option to include where clause except the CountDistinct Analyzer.
I am looking for a use case of distinct count of col_a  where col_b = '0' .  I can pass filtered df for achieving this, however having additional set of analyzers on the unfiltered data set, I am thinking if it can be achieved with one go without passing a new data set.

**Comment by sscdotopen** [comment]
We only provide filters for the analyzers which do not require us to re-partition (shuffle) the data for performance reasons.

**Comment by mschandra18** [comment]
ok, got it.
