### ISSUE TITLE
Treatment of empty string in constraints and profiling

### ISSUE THREAD

**Issue by dwsmith1983** [awslabs/deequ#315]
When running check constraints, empty strings are not treated as null; however, when profiling, empty strings are treated as null which are integral type. Is the inconsistent treatment of empty strings intentional?

This is on 1.0.5, Spark 2.3.0, and Scala 2.11.8

Note some_column is a single column.

`Column 'some_column':
 	completeness: 1.0
	approximate number of distinct values: 12054758
	datatype: String
	typeCounts: Map(Boolean -> 0, Fractional -> 0, Integral -> 1334939, Unknown -> 0, String -> 10925770429)
	histogram: None
	data type inferred: true`

Here from profiling, I see that this column has over a million integral type which would be very bad for exposing personal information. However, upon investigation 

`df.select("some_column").where($"some_column" === "").count
1334939
 df.select("some_column").where($"some_column".isNull).count
0
`

Now when I run constraints suggestions, I see

`Constraint suggestion for 'some_column':	'some_column' is not null
The corresponding scala code is .isComplete("some_column")`

This suggestion couldn't be true if "" is being treated as a null. In another suggestion, I have

`The corresponding scala code is .isContainedIn("another_column", Array(""), _ >= 0.96, Some("It should be above 0.96!"))`

Should the treatment of empty strings be consistent?

**Comment by academy-codex** [comment]
@dwsmith1983 I feel the profiling was fixed in #307.

**Comment by dwsmith1983** [comment]
> @dwsmith1983 I feel the profiling was fixed in #307.
@academy-codex 
Thanks for the info. I haven't worked on this for sometime now at work. Others are maintaining it but thanks for the update. I will leave this open until a contributor closes for being fixed.
