### ISSUE TITLE
travis setup still relevant?

### ISSUE THREAD

**Issue by twollnik** [awslabs/deequ#326]
@sscdotopen 

The Makefile includes the target `travis-deploy`. This target is called in the `.travis.yml` in the `deploy` stage. As far as I know, we are doing manual deployments using a runbook. Is the travis setup with the `deploy` stage and the make target `travis-deploy` still relevant?

**Comment by sscdotopen** [comment]
No, feel free to remove that.

**Comment by twollnik** [comment]
Thanks for the quick reply. I will open a PR.
