### ISSUE TITLE
Any possibility Scala or Java Documentation?

### ISSUE THREAD

**Issue by nitendragautam** [awslabs/deequ#335]
I have a requirement when I need to implement Data quality check as a part of ETL pipeline.
I am thinking of using Amazon Deequ library instead of writing from the scratch. I see the documentation for python https://pydeequ.readthedocs.io/en/latest/index.html 

Is there a plan document for this library like above if want to use Scala or Java?

**Comment by SerenaLin2020** [comment]
@nitendragautam There are lots of examples and unit test for the Deequ Scala. Here https://github.com/awslabs/deequ/tree/master/src/main/scala/com/amazon/deequ/examples and here https://github.com/awslabs/deequ/tree/master/src/test/scala/com/amazon/deequ. 
Seems that the fastest way to get the tutorial is by reading the code and the example. The overall is simple and not that hard to understand.

**Comment by nitendragautam** [comment]
@SerenaLin2020  Thanks. i will take a look.
