### ISSUE TITLE
DeeQu is not running with Scala 2.12

### ISSUE THREAD

**Issue by Zamlos** [awslabs/deequ#348]
Hi, I tried to run Deequ using the workaround [here](https://github.com/awslabs/deequ/issues/193) exposed. Nevertheless, when I run the job I get the following error. 

`Exception in thread "main" java.lang.NoClassDefFoundError: com/amazon/deequ/analyzers/Analyzer
	at com.deequ_unit_tests.DeeQu_experiment.main(DeeQu_unit_tests.scala)
Caused by: java.lang.ClassNotFoundException: com.amazon.deequ.analyzers.Analyzer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more`
	
When I run it using Scala 2.11 it works correctly. Unfortunately, due to a change in the cluster properties, I need to run this job using version 2.12 now.

**Comment by alexott** [comment]
yes, because of the incorrect dependencies:

```
[INFO] \- com.amazon.deequ:deequ:jar:1.1.0_spark-3.0-scala-2.12:compile
[INFO]    +- org.scala-lang:scala-library:jar:2.11.10:compile
[INFO]    +- org.apache.spark:spark-core_2.11:jar:2.4.2:compile
[INFO]    |  +- com.twitter:chill_2.11:jar:0.9.3:compile
```

**Comment by MrPowers** [comment]
@alexott - Looks like the Spark 3 Deequ JAR file is depending on Scala 2.11 stuff and is broken.  There might be a work-around in some runtimes, but this JAR file will be problematic for any projects depending on SBT dependency resolution.

I think you're raising a valid error @Zamlos.

<img width="1236" alt="Screen Shot 2021-03-21 at 8 48 08 AM" src="https://user-images.githubusercontent.com/2722395/111903681-410fae80-8a22-11eb-9fcd-43380c2d204b.png">

**Comment by alexott** [comment]
@MrPowers yes - it looks like a problem with profiles...

**Comment by MrPowers** [comment]
@alexott - I created [a separate issue](https://github.com/awslabs/deequ/issues/353) to explain the status-quo and a good path forward.  Hopefully we can get the publishing process fixed cause this is a really valuable library for the community.

**Comment by lange-labs** [comment]
Resolving per #353, #361
