### ISSUE TITLE
Please update Maven , sbt dependency

### ISSUE THREAD

**Issue by ritesh-codebrew** [awslabs/deequ#351]
The Deequ repo is hosted at the following link: 
https://repo1.maven.org/maven2/com/amazon/deequ/deequ/1.1.0_spark-3.0-scala-2.12/deequ-1.1.0_spark-3.0-scala-2.12.pom
But the following maven , sbt dependency leads to the following link:
https://repo1.maven.org/maven2/com/amazon/deequ/deequ/1.1.0-spark-3.0-scala-2.12/deequ-1.1.0-spark-3.0-scala-2.12.pom
Please update the dependencies in README file accordingly.

**Comment by twollnik** [comment]
implemented in https://github.com/awslabs/deequ/pull/347
