### ISSUE TITLE
Running mutiple deequ function in single expression

### ISSUE THREAD

**Issue by rahulgoyal2987** [awslabs/deequ#369]
I want to run mutiple deequ function in single expression
For example
column1 in range of min(column2) and max(column2)
Is there there a way to do this in one run of deequ

**Comment by sscdotopen** [comment]
Deequ will automatically generates queries to compute these aggregates in a single pass. No need for manual SQL :)

**Comment by rahulgoyal2987** [comment]
Can you share some example how it this work?

**Comment by sscdotopen** [comment]
This happens automatically, just use Deequ as shown in our examples from https://github.com/awslabs/deequ
