### ISSUE TITLE
Support for Spark 3.1.x

### ISSUE THREAD

**Issue by ashwin153** [awslabs/deequ#372]
I see #366 adds support for Spark 3.1 but is not backwards compatible. Are there plans to support Spark 3.1, or is there no way to add support without dropping compatibility?

**Comment by twollnik** [comment]
We currently are not aware of a way to add spark 3.1. compatibility AND keep 2.x compatibility. Sadly, we can't drop 2.x compatibility. Thus, we have no immediate plan to support spark 3.1.

**Comment by humanzz** [comment]
@twollnik I wonder if it's the right thing to actually close this issue. It's clearly a very valid feature request and I was coming here specifically to check for 3.1.x compatibility and to open a feature request if it's not yet supported.

I did see the discussion in https://github.com/awslabs/deequ/pull/366 and I understand not wanting to drop the 2.x compatibility of course. That does not take away from the fact that 3.1.x support is being requested from Deequ and at some point a solution for this has to be found and the github issue is the best way for us - Deequ users - to communicate and provide interest and feedback and I don't imagine you want to have duplicate issues all asking for such support.

**Comment by sscdotopen** [comment]
I agree and I think we should have a 3.1x branch/release.

**Comment by sscdotopen** [comment]
I would suggest to make a maintenance branch with support for Spark 2.x and only backport bugfixes in this branch, and switch to Spark 3.1 for the master branch.

**Comment by humanzz** [comment]
+1 to @sscdotopen's comments

**Comment by twollnik** [comment]
spark 3.1 release is done. please re-open in case of any issues.
