### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by quintusvw** [awslabs/deequ#374]
I installed Deequ on my AWS account using the CloudFormation template found [here](https://aws.amazon.com/blogs/big-data/building-a-serverless-data-quality-and-analysis-framework-with-deequ-and-aws-glue/).

It is set up correctly, and I have created the database and table in Glue that it must access and have tested it using the IAM role created by CloudFormation. When executing the step function the data-quality-suggestion-analysis-verification-runner job in glue fails with the following error:

`Exception in User Class: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException : Communications link failure`

I have set up my RDS with the "All TCP" inbound rule.

Why would it fail on the connection part?

**Comment by lange-labs** [comment]
This problem seems to be related to Glue/RDS connection issues. Unfortunately, we cannot provide support for that use case as part of the Deequ package. Closing.
