### ISSUE TITLE
Documentation for core concepts in our library

### ISSUE THREAD

**Issue by stefan-grafberger** [awslabs/deequ#41]
Do we need a separate markdown file where we explain all core concepts like analyzers, checks, constraints, metrics, column profiles, metric repositories, check levels etc.?

We should also have a list of all analyzers, constraints, anomaly detection methods and constraint suggestion rules we offer in one place.

Maybe even a readthedocs-documentation?

**Comment by stefan-grafberger** [comment]
We also need to explain basic analyzers vs advanced (expensive) analyzers.

**Comment by lange-labs** [comment]
Resolved through PR #234
