### ISSUE TITLE
Support for Referential Integrity

### ISSUE THREAD

**Issue by stefan-grafberger** [awslabs/deequ#42]
We would like to support referential integrity constraints and analyzers.

**Comment by parisni** [comment]
FK validation constraint might looks like:

``` scala
// when one source/target column involved in the relation
 .hasForeignKey(customers, "customerId" -> "id")
// when multiple source/target columns
 .hasForeignKey(customers, ("customerId", "version") -> ("id", "version"))
```

Do you think about something like that ?

**Comment by sscdotopen** [comment]
In general yes, the problem is that deequ is only designed to handle one dataframe at the moment, so its not totally obvious how to extend this to another one.

**Comment by parisni** [comment]
> deequ is only designed to handle one dataframe at the moment

adding the FK as a column to that dataframe with a left join before the processing  and converting the `hasForeignKey` into  a `isComplete("fk")` is a workaround i can think of with the current set of tools you provide

**Comment by harananikesh** [comment]
any further progress on this? It is really good to have feature.
