### ISSUE TITLE
deequ not running on Spark version 3.3.0 and Databricks Runtime 11.0

### ISSUE THREAD

**Issue by TheDataDexter** [awslabs/deequ#427]
I am trying to update my Databricks runtime to the newest version (DBR 11.0). However, the deequ package is not being installed properly. On the older Databricks runtimes the package is installed with no problems.

MAVEN coordinates: com.amazon.deequ:deequ:2.0.1-spark-3.2

DBR 11.0 configurations:
- Scala version: 2.12
- Spark version: 3.3.0

DBR 10.5 configurations:
 - Scala version: 2.12
 - Spark version 3.2.1

Error Code: `DRIVER_LIBRARY_INSTALLATION_FAILURE.`
Error Message: `Library resolution failed because problem during retrieve of com.databricks#dbc-parent: java.lang.RuntimeException: Multiple artifacts of the module net.sourceforge.f2j#arpack_combined_all;0.1 are retrieved to the same file! Update the retrieve pattern  to fix this error.`

**Comment by saikiran-reddy** [comment]
did you find a solution for this issue?

**Comment by saikiran-reddy** [comment]
Hi, I am facing the same issue. Were you able to find a solution for it?

**Comment by rdsharma26** [comment]
@TheDataDexter @saikiran-reddy We have released a [new version](https://github.com/awslabs/deequ/tree/2.0.2) of Deequ `2.0.2` which depends on Spark `3.3.0`.

Can you try installing the updated version?
