### ISSUE TITLE
Deequ for Spark 3.3.0

### ISSUE THREAD

**Issue by 10hith** [awslabs/deequ#437]
Just checking to see if there is a release slated for Spark 3.3.0

**Comment by raghachellappa** [comment]
We too (in our project) are looking for a version of Deequ that is compatible with Spark 3.3.0. Is there any timelines/tentative ETA for this? Will appreciate any details on this.

**Comment by giovannipapini-agilelab** [comment]
Same here, is there any news?

**Comment by shehzad-qureshi** [comment]
duplicate of #442 . we're working on cutting an official release soon.

**Comment by lsgrep** [comment]
@shehzad-qureshi  Hi Thank you very much for the work. Is there a release date for the 3.3.0 official release?

**Comment by shehzad-qureshi** [comment]
apologies for the delay. 3.3.0 has been released to maven and has been tagged in this repo.
