### ISSUE TITLE
DQDL example for Time-series

### ISSUE THREAD

**Issue by jinman** [awslabs/deequ#456]
Are there any examples DQDL for Time-series data that automatically suggest the best practices for frequency, missing value, range, datatypes etc?

**Comment by rdsharma26** [comment]
Hello @jinman 
DQDL is not a part of the Deequ Github project yet. Unfortunately, we do not have these kind of examples for DQDL. 
Please proceed with opening a support ticket for AWS Glue through your AWS Account. Someone from the service team will be able to look at your request and assist you.
