### ISSUE TITLE
Update Deequ to Spark 3.4

### ISSUE THREAD

**Issue by jklap** [awslabs/deequ#481]
We are currently using Databricks w/Deequ using an older Databricks runtime that has Spark 3.3.0 in it.

Unfortunately we need to update to a more recent Databricks runtime due some feature updates -- but that means we are moving to Spark 3.4.0.

Please consider this a request to update Deequ to support Spark 3.4.0

**Comment by jhchee** [comment]
Does anyone has success using this with Spark 3.4?

**Comment by eycho-am** [comment]
Merged PR #505 to add Spark 3.4.0 support

**Comment by chenliu0831** [comment]
Could we release this to Maven?
