### ISSUE TITLE
Is this library can be used with other Technolgy rather than Spark, such as Flink for example?

### ISSUE THREAD

**Issue by abeermohamed1** [awslabs/deequ#497]
**Ask questions that don't apply to the other templates (Bug report, Feature request)**

**Comment by mentekid** [comment]
Hi,

Thanks for the question.

Deequ has a dependency on Spark, so it cannot be used on an environment where Spark is not present.

**Comment by stefan-grafberger** [comment]
If anyone is interested in something like Deequ but for Flink, we built a prototype for a comparable streaming data quality library for Apache Flink: [StreamDQ](https://github.com/stefan-grafberger/StreamDQ). However, it is only a prototype so far, and we have no resources currently to continue building it. However, if someone wants to build something like this, StreamDQ might be a very good starting point. All the basic functionality already works there, it just is not very robust yet and more checks, etc. need to be implemented.
