### ISSUE TITLE
Release cadence?

### ISSUE THREAD

**Issue by marcantony** [awslabs/deequ#575]
It looks like releases are fairly infrequent - the last one was on [July 2](https://github.com/awslabs/deequ/releases/tag/2.0.7) and before that, [November 13](https://github.com/awslabs/deequ/releases/tag/2.0.6). How quickly can we expect new releases of the project to be published once changes are made?

**Comment by mentekid** [comment]
We do not currently have a set cadence for releases, although we would like to automate our release process to at least push the latest changes to Maven for the highest spark version (Spark 3.5). So far we have been releasing when a large enough body of changes is ready to go.

**Comment by marcantony** [comment]
Thanks for the info!
