### ISSUE TITLE
No histgram for boolean columns?

### ISSUE THREAD

**Issue by hangelwen** [awslabs/deequ#59]
Example:
```
"column_hasVisit": {
      "column": "column_hasVisit",
      "completeness": 1,
      "approximateNumDistinctValues": 2,
      "dataType": {
        "enumClass": "com.amazon.deequ.analyzers.DataTypeInstances",
        "value": "Boolean"
      },
      "isDataTypeInferred": false,
      "typeCounts": {},
      "histogram": null
    }
```

**Comment by sscdotopen** [comment]
Dear Jack,

Thank you for the hint, this is a bug that we need to fix.

**Comment by sscdotopen** [comment]
@hangelwen we pushed a fix for this, thanks again for finding the bug! We will cut a new release and let you know once that is available.

**Comment by tdhd** [comment]
@hangelwen We've released an updated version of deequ which includes the fix (https://github.com/awslabs/deequ/releases/tag/1.0.0-rc3).
