### ISSUE TITLE
Has anyone successfully used this in combination with AWS Glue?

### ISSUE THREAD

**Issue by brentstrong** [awslabs/deequ#80]
Hoping to use this in conjunction with Glue to automate testing into our data pipeline. Has anyone done this successfully? 

I'm attempting to run the BasicExample.scala code using a SageMaker notebook attached to a Glue Development Endpoint. I'm working in the SparkMagic kernel.

**Comment by sscdotopen** [comment]
Hi Brent,

I haven't heard of a Glue use case yet, but let us know if there are other things that we can help with.

Best,
Sebastian

**Comment by brentstrong** [comment]
Thanks! If I get something working, I'll share it.

**Comment by jospas** [comment]
Hi @brentstrong  did you get this working in Glue?

Josh

**Comment by brentstrong** [comment]
I did not, but to be fair it was almost a year ago, so Glue may have added capabilities, and I'm not very familiar with Scala in general. So I wouldn't say to take it as a dead end, but it wasn't successful for me. 

I may try again sometime soon if I get some time. Would be interested if anyone else makes progress!

**Comment by jospas** [comment]
Thank you!

**Comment by jaidisido** [comment]
Hi, we have created an artifact to run Deequ on AWS Glue: https://github.com/aws-samples/amazon-deequ-glue
Don't forget to star if you like it :)

**Comment by sscdotopen** [comment]
Awesome thanks!
