### ISSUE TITLE
Create an example for data profiling

### ISSUE THREAD

**Issue by sscdotopen** [awslabs/deequ#9]
Create an example for using our [single-column data profiling](src/main/scala/com/amazon/deequ/suggestions/ColumnProfiler.scala) to profile data.

**Comment by hangelwen** [comment]
+1 for this. I'm exploring this lib for our data quality monitoring use case. Could you add some examples for this? Thanks.

**Comment by sscdotopen** [comment]
Hi, we're happy to hear that your exploring the use of deequ! We'll provide you with this example soon.
