### ISSUE TITLE
Histogram analysis for categorical data with numerical values

### ISSUE THREAD

**Issue by paulsukow** [awslabs/deequ#95]
It is possible of have categorical data with numerical values.
For example 1 indicating male and 2 indicating female. 

It would be nice be have histogram analysis available for those columns. Currently, it is limited to only boolean and string columns

**Comment by sscdotopen** [comment]
Hi Paul,

Happy to see that you are using Deequ! Actually, histograms on numeric columns should work, I wrote a test for this here https://github.com/awslabs/deequ/pull/96 .

Can you provide us with more details about the error that you are seeing?

Best,
Sebastian

**Comment by paulsukow** [comment]
@sscdotopen I was using the column profiler and the histogram analysis was only working with String and boolean columns. On further investigation I found this code in ColumnProfiler.scala
`
/* Identifies all columns, which:
   *
   * (1) have type string or boolean
   * (2) have less than `lowCardinalityHistogramThreshold` approximate distinct values
   */
  private[this] def findTargetColumnsForHistograms(
      schema: StructType,
      genericStatistics: GenericColumnStatistics,
      lowCardinalityHistogramThreshold: Long)
    : Seq[String] = {

    val originalStringOrBooleanColumns = schema
      .flatMap { field =>
        if (field.dataType == StringType || field.dataType == BooleanType) {
          Some(field.name)
        } else {
          None
        }
      }
      .toSet
`

**Comment by paulsukow** [comment]
I could be wrong, but it looks like the column profiler is filtering out the numeric columns before using the histogram class you wrote the test for. Thanks for the quick response btw. Deequ is pretty sweet so far

**Comment by sscdotopen** [comment]
Ah, good find. You are right that we do not consider low-cardinality numeric columns as categorical here. Would you like to write a PR to fix this?

**Comment by paulsukow** [comment]
Ya, I'll write up a pr later today.

**Comment by paulsukow** [comment]
pr for fix https://github.com/awslabs/deequ/pull/97

**Comment by paulsukow** [comment]
#97 merged. Closing issue
