### ISSUE TITLE
help: Compile Error libraryDependencies 

### ISSUE THREAD

**Issue by tatacoa** [awslabs/deequ#99]
Hi, I'm using Apache Toree - Scala Notebook. Sacla version 2.11.8 and java version"1.8.0_191", in Ubuntu. I'm getting this error while trying to  install the required library to use dequee

![image](https://user-images.githubusercontent.com/35470096/56741194-aa251380-6772-11e9-8415-98094e00eac5.png)

Any suggestions? Thanks

**Comment by tatacoa** [comment]
according to the documentation https://toree.apache.org/docs/current/user/faq/ the dependencies should be added like 
![image](https://user-images.githubusercontent.com/35470096/56744394-b57b3d80-6778-11e9-911f-b351ab13692a.png)
but is taking very long to run!

**Comment by tatacoa** [comment]
so, After running the AddDeps line, there was no file downloaded from amazon.dequee
![image](https://user-images.githubusercontent.com/35470096/56746244-1e17e980-677c-11e9-97de-6cff347c9be7.png)

**Comment by sscdotopen** [comment]
Hi, I have not tried Toree myself yet. But I think the correct command should be this:

``` 
%AddDeps com.amazon.deequ deequ 1.0.1
```

Can you try that?

**Comment by sscdotopen** [comment]
You might also need the --transitive flag

**Comment by tatacoa** [comment]
> Hi, I have not tried Toree myself yet. But I think the correct command should be this:
> 
> ```
> %AddDeps com.amazon.deequ deequ 1.0.1
> ```
> Can you try that?

Sure, it works!

**Comment by sscdotopen** [comment]
Happy to hear that!

**Comment by tatacoa** [comment]
Thanks for your help!
